// AUTO-GENERATED - Do not edit this file directly.
#![allow(warnings)]
//! https://drafts.csswg.org/filter-effects-2/

mod impls;
use super::prelude::*;
use impls::*;
// /// Represents the style value for `backdrop-filter` as defined in [filter-effects-2](https://drafts.csswg.org/filter-effects-2/#backdrop-filter).
// ///
// /// The backdrop-filter CSS property applies graphical effects such as blurring or color shifting to the area behind an element.
// ///
// /// The grammar is defined as:
// ///
// /// ```text,ignore
// /// none | <filter-value-list>
// /// ```
// ///
// /// https://drafts.csswg.org/filter-effects-2/#backdrop-filter
// #[syntax(" none | <filter-value-list> ")]
// #[derive(
//     Parse,
//     Peek,
//     ToSpan,
//     ToCursors,
//     DeclarationMetadata,
//     SemanticEq,
//     Debug,
//     Clone,
//     PartialEq,
//     Eq,
//     PartialOrd,
//     Ord,
//     Hash,
// )]
// #[declaration_metadata(
//     initial = "none",
//     applies_to = Unknown,
//     animation_type = Unknown,
//     property_group = FilterEffects,
//     computed_value_type = AsSpecified,
//     canonical_order = "per grammar",
// )]
// #[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
// #[cfg_attr(
//     feature = "css_feature_data",
//     derive(ToCSSFeature),
//     css_feature("css.properties.backdrop-filter")
// )]
// #[cfg_attr(feature = "visitable", derive(Visitable), visit)]
// pub struct BackdropFilterStyleValue;

/// Represents the style value for `color-interpolation-filters` as defined in [filter-effects-2](https://drafts.csswg.org/filter-effects-2/#color-interpolation-filters).
///
/// The <filter> SVG element applies custom effects such as color manipulation, blurring, or morphing to SVG elements.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | sRGB | linearRGB
/// ```
///
/// https://drafts.csswg.org/filter-effects-2/#color-interpolation-filters
#[syntax(" auto | sRGB | linearRGB ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "linearRGB",
    inherits,
    applies_to = Unknown,
    animation_type = Discrete,
    property_group = FilterEffects,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(
	feature = "css_feature_data",
	derive(ToCSSFeature),
	css_feature("css.properties.color-interpolation-filters")
)]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub enum ColorInterpolationFiltersStyleValue {}

// /// Represents the style value for `filter` as defined in [filter-effects-2](https://drafts.csswg.org/filter-effects-2/#filter).
// ///
// /// The filter CSS property applies one or more graphic effects to an element. You can use filter functions, such as blur() and drop-shadow(), alone or combined to produce different effects.
// ///
// /// The grammar is defined as:
// ///
// /// ```text,ignore
// /// none | <filter-value-list>
// /// ```
// ///
// /// https://drafts.csswg.org/filter-effects-2/#filter
// #[syntax(" none | <filter-value-list> ")]
// #[derive(
//     Parse,
//     Peek,
//     ToSpan,
//     ToCursors,
//     DeclarationMetadata,
//     SemanticEq,
//     Debug,
//     Clone,
//     PartialEq,
//     Eq,
//     PartialOrd,
//     Ord,
//     Hash,
// )]
// #[declaration_metadata(
//     initial = "none",
//     applies_to = Unknown,
//     animation_type = Unknown,
//     property_group = FilterEffects,
//     computed_value_type = AsSpecified,
//     canonical_order = "per grammar",
// )]
// #[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
// #[cfg_attr(
//     feature = "css_feature_data",
//     derive(ToCSSFeature),
//     css_feature("css.properties.filter")
// )]
// #[cfg_attr(feature = "visitable", derive(Visitable), visit)]
// pub struct FilterStyleValue;

/// Represents the style value for `flood-color` as defined in [filter-effects-2](https://drafts.csswg.org/filter-effects-2/#flood-color).
///
/// The <filter> SVG element applies custom effects such as color manipulation, blurring, or morphing to SVG elements.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <color>
/// ```
///
/// https://drafts.csswg.org/filter-effects-2/#flood-color
#[syntax(" <color> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "black",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    property_group = FilterEffects,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.flood-color"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct FloodColorStyleValue;

/// Represents the style value for `flood-opacity` as defined in [filter-effects-2](https://drafts.csswg.org/filter-effects-2/#flood-opacity).
///
/// The <filter> SVG element applies custom effects such as color manipulation, blurring, or morphing to SVG elements.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <'opacity'>
/// ```
///
/// https://drafts.csswg.org/filter-effects-2/#flood-opacity
#[syntax(" <'opacity'> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "1",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    property_group = FilterEffects,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.flood-opacity"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct FloodOpacityStyleValue;

/// Represents the style value for `lighting-color` as defined in [filter-effects-2](https://drafts.csswg.org/filter-effects-2/#lighting-color).
///
/// The <filter> SVG element applies custom effects such as color manipulation, blurring, or morphing to SVG elements.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <color>
/// ```
///
/// https://drafts.csswg.org/filter-effects-2/#lighting-color
#[syntax(" <color> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "white",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    property_group = FilterEffects,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.lighting-color"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct LightingColorStyleValue;
