// AUTO-GENERATED from w3c/csswg-drafts
// Commit: https://github.com/w3c/csswg-drafts/commit/4401d6101f52bec41fe998fdc46c417453e10b61
// Do not edit this file directly.
#![allow(warnings)]
//! https://drafts.csswg.org/css-scrollbars-1/

mod impls;
use super::prelude::*;
use impls::*;
/// Represents the style value for `scrollbar-color` as defined in [css-scrollbars-1](https://drafts.csswg.org/css-scrollbars-1/#scrollbar-color).
///
/// The scrollbar-color CSS property sets the color of the scrollbar track and thumb.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | <color>{2}
/// ```
///
/// https://drafts.csswg.org/css-scrollbars-1/#scrollbar-color
#[syntax(" auto | <color>{2} ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    inherits,
    applies_to = Unknown,
    animation_type = ByComputedValue,
    property_group = Scrollbars,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.scrollbar-color"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct ScrollbarColorStyleValue;

/// Represents the style value for `scrollbar-width` as defined in [css-scrollbars-1](https://drafts.csswg.org/css-scrollbars-1/#scrollbar-width).
///
/// The scrollbar-width CSS property sets the width of the scrollbar.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | thin | none
/// ```
///
/// https://drafts.csswg.org/css-scrollbars-1/#scrollbar-width
#[syntax(" auto | thin | none ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = Discrete,
    property_group = Scrollbars,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.scrollbar-width"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub enum ScrollbarWidthStyleValue {}
