#!/usr/bin/env sh
#MISE description = "Run code generation to build all CSS style values"
#MISE sources = ["./tasks/generate-values/.*-cache.txt", "./tasks/generate-values/mod.ts", "crates/css_ast/src/values/**/*.rs"]
cd "$(dirname "$0")/generate-values" || exit

# Generate all values
if [ ! -f ".caches/index.json" ]; then
	# Fetch a spec to allow the index.json cache to be primed.
	deno --allow-net --allow-read --allow-write mod.ts align
fi
for f in $(jq <.caches/index.json '.tree.[] | select(.path | startswith("css-")) | .path | sub("css-"; "") | sub("-[0-9]+$"; "") | select(test("^[0-9]+$") | not)' --raw-output | sort -u); do
	if [ "${f}" = "mobile" ] || [ "${f}" = "module" ] || [ "${f}" = "print" ] || [ "${f}" = "tv" ]; then continue; fi
	echo "Building mod.rs for ${f}"
	echo "========================="
	deno --allow-net --allow-read --allow-write mod.ts "${f}"
done
