// AUTO-GENERATED from w3c/csswg-drafts
// Commit: https://github.com/w3c/csswg-drafts/commit/7b25446fac9b00358a4e887b2543ad77bc1359be
// Do not edit this file directly.
#![allow(warnings)]
//! https://drafts.csswg.org/css-link-params-1/

mod impls;
use super::prelude::*;
use impls::*;
/// Represents the style value for `link-parameters` as defined in [css-link-params-1](https://drafts.csswg.org/css-link-params-1/#link-parameters).
///
/// The link-parameters CSS property, param() modifier for the url() CSS function, and the #:~:param(…) URL fragment set custom CSS environment variables on an external resource, such as an SVG image, allowing the external resource to adapt its presentation based on the variables.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// none | <param()>#
/// ```
///
/// https://drafts.csswg.org/css-link-params-1/#link-parameters
#[syntax(" none | <param()># ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "none",
    applies_to = Elements|PseudoElements,
    animation_type = Discrete,
    property_group = LinkParams,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.link-parameters"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
#[derive(csskit_derives::NodeWithMetadata)]
pub struct LinkParametersStyleValue<'a>;
