mod absolute_size;
mod anchor_name;
mod animateable_feature;
mod animation_action;
mod attachment;
mod auto;
mod auto_line_color_list;
mod auto_line_style_list;
mod auto_line_width_list;
mod auto_or;
mod auto_repeat;
mod autonone_or;
mod autospace;
mod baseline_metric;
mod baseline_position;
mod basic_shape;
mod basic_shape_rect;
mod bg_clip;
mod bg_layer;
mod bg_position;
mod bg_position_and_size;
mod bg_size;
mod blend_mode;
mod border_radius;
mod color;
mod color_scheme_name;
mod common_lig_values;
mod compat_auto;
mod compat_special;
mod compositing_operator;
mod content_alt_item;
mod content_distribution;
mod content_level;
mod content_list;
mod content_position;
mod contextual_alt_values;
mod coord_box;
mod corner_shape_value;
mod counter_name;
mod counter_style;
mod cursor_image;
mod cursor_predefined;
mod custom_ident;
mod dashed_ident;
mod discretionary_lig_values;
mod display_box;
mod display_inside;
mod display_internal;
mod display_legacy;
mod display_legacy_vendor;
mod display_listitem;
mod display_outside;
mod east_asian_variant_values;
mod east_asian_width_values;
mod event_trigger_event;
mod feature_tag_value;
mod fill_layer;
mod fill_origin;
mod fixed_breadth;
mod fixed_repeat;
mod fixed_size;
mod font_family_name;
mod font_weight_absolute;
mod gap_auto_rule_list;
mod gap_rule_list;
mod generic_font_family;
mod generic_voice;
mod geometry_box;
mod grid_line;
mod historical_lig_values;
mod image;
mod image_1d;
mod inflexible_breadth;
mod inset_value;
mod integer_or_infinite;
mod isolation_mode;
mod layout_box;
mod line_color_list;
mod line_color_or_repeat;
mod line_names;
mod line_style;
mod line_style_list;
mod line_style_or_repeat;
mod line_width_list;
mod line_width_or_repeat;
mod mask_layer;
mod mask_reference;
mod masking_mode;
mod name_repeat;
mod none_or;
mod normal_or;
mod numeric_figure_values;
mod numeric_fraction_values;
mod numeric_spacing_values;
mod offset_path;
mod opacity_value;
mod opentype_tag;
mod outline_style;
mod overflow_position;
mod paint;
mod paint_box;
mod palette_identifier;
mod position;
mod position_and_size;
mod position_area;
mod positive_non_zero_int;
mod quote;
mod ratio;
mod relative_size;
mod repeat_line_color;
mod repeat_line_style;
mod repeat_line_width;
mod repeat_style;
mod reversed_counter_name;
mod self_position;
mod shadow;
mod shape_box;
mod shape_command;
mod single_animation;
mod single_animation_composition;
mod single_animation_direction;
mod single_animation_fill_mode;
mod single_animation_iteration_count;
mod single_animation_play_state;
mod single_animation_timeline;
mod single_animation_trigger;
mod single_animation_trigger_behavior;
mod single_animation_trigger_type;
mod single_transition;
mod single_transition_property;
mod spacing_trim;
mod spread_shadow;
mod stroke_layer;
mod svg_paint;
mod syntax;
mod target_name;
mod text_edge;
mod text_overflow_single_axis;
mod timeline_range_center_subject;
mod timeline_range_name;
mod track_breadth;
mod track_list;
mod track_repeat;
mod track_size;
mod transform_list;
mod transition_behavior_value;
mod try_size;
mod try_tactic;
mod variation_tag_value;
mod visual_box;
mod voice_family_name;

pub use absolute_size::*;
pub use anchor_name::*;
pub use animateable_feature::*;
pub use animation_action::*;
pub use attachment::*;
pub use auto::*;
pub use auto_line_color_list::*;
pub use auto_line_style_list::*;
pub use auto_line_width_list::*;
pub use auto_or::*;
pub use auto_repeat::*;
pub use autonone_or::*;
pub use autospace::*;
pub use baseline_metric::*;
pub use baseline_position::*;
pub use basic_shape::*;
pub use basic_shape_rect::*;
pub use bg_clip::*;
pub use bg_layer::*;
pub use bg_position::*;
pub use bg_position_and_size::*;
pub use bg_size::*;
pub use blend_mode::*;
pub use border_radius::*;
pub use color::*;
pub use color_scheme_name::*;
pub use common_lig_values::*;
pub use compat_auto::*;
pub use compat_special::*;
pub use compositing_operator::*;
pub use content_alt_item::*;
pub use content_distribution::*;
pub use content_level::*;
pub use content_list::*;
pub use content_position::*;
pub use contextual_alt_values::*;
pub use coord_box::*;
pub use corner_shape_value::*;
pub use counter_name::*;
pub use counter_style::*;
pub use cursor_image::*;
pub use cursor_predefined::*;
pub use custom_ident::*;
pub use dashed_ident::*;
pub use discretionary_lig_values::*;
pub use display_box::*;
pub use display_inside::*;
pub use display_internal::*;
pub use display_legacy::*;
pub use display_legacy_vendor::*;
pub use display_listitem::*;
pub use display_outside::*;
pub use east_asian_variant_values::*;
pub use east_asian_width_values::*;
pub use event_trigger_event::*;
pub use feature_tag_value::*;
pub use fill_layer::*;
pub use fill_origin::*;
pub use fixed_breadth::*;
pub use fixed_repeat::*;
pub use fixed_size::*;
pub use font_family_name::*;
pub use font_weight_absolute::*;
pub use gap_auto_rule_list::*;
pub use gap_rule_list::*;
pub use generic_font_family::*;
pub use generic_voice::*;
pub use geometry_box::*;
pub use grid_line::*;
pub use historical_lig_values::*;
pub use image::*;
pub use image_1d::*;
pub use inflexible_breadth::*;
pub use inset_value::*;
pub use integer_or_infinite::*;
pub use isolation_mode::*;
pub use layout_box::*;
pub use line_color_list::*;
pub use line_color_or_repeat::*;
pub use line_names::*;
pub use line_style::*;
pub use line_style_list::*;
pub use line_style_or_repeat::*;
pub use line_width_list::*;
pub use line_width_or_repeat::*;
pub use mask_layer::*;
pub use mask_reference::*;
pub use masking_mode::*;
pub use name_repeat::*;
pub use none_or::*;
pub use normal_or::*;
pub use numeric_figure_values::*;
pub use numeric_fraction_values::*;
pub use numeric_spacing_values::*;
pub use offset_path::*;
pub use opacity_value::*;
pub use opentype_tag::*;
pub use outline_style::*;
pub use overflow_position::*;
pub use paint::*;
pub use paint_box::*;
pub use palette_identifier::*;
pub use position::*;
pub use position_and_size::*;
pub use position_area::*;
pub use positive_non_zero_int::*;
pub use quote::*;
pub use ratio::*;
pub use relative_size::*;
pub use repeat_line_color::*;
pub use repeat_line_style::*;
pub use repeat_line_width::*;
pub use repeat_style::*;
pub use reversed_counter_name::*;
pub use self_position::*;
pub use shadow::*;
pub use shape_box::*;
pub use shape_command::*;
pub use single_animation::*;
pub use single_animation_composition::*;
pub use single_animation_direction::*;
pub use single_animation_fill_mode::*;
pub use single_animation_iteration_count::*;
pub use single_animation_play_state::*;
pub use single_animation_timeline::*;
pub use single_animation_trigger::*;
pub use single_animation_trigger_behavior::*;
pub use single_animation_trigger_type::*;
pub use single_transition::*;
pub use single_transition_property::*;
pub use spacing_trim::*;
pub use spread_shadow::*;
pub use stroke_layer::*;
pub use svg_paint::*;
pub use syntax::*;
pub use target_name::*;
pub use text_edge::*;
pub use text_overflow_single_axis::*;
pub use timeline_range_center_subject::*;
pub use timeline_range_name::*;
pub use track_breadth::*;
pub use track_list::*;
pub use track_repeat::*;
pub use track_size::*;
pub use transform_list::*;
pub use transition_behavior_value::*;
pub use try_size::*;
pub use try_tactic::*;
pub use variation_tag_value::*;
pub use visual_box::*;
pub use voice_family_name::*;

mod prelude {
	pub(crate) use crate::CssAtomSet;
	pub(crate) use css_parse::Vec;
	pub(crate) use css_parse::{
		Cursor, Diagnostic, Kind, KindSet, Parse, Parser, Peek, Result as ParserResult, T, ToNumberValue,
	};
	pub(crate) use csskit_derives::*;
	pub(crate) use csskit_proc_macro::{node, syntax};
}

// Type aliases for primitive CSS types referenced in syntax definitions
pub type Integer = crate::CSSInt;
pub type IntegerInfinite<'a> = crate::IntegerOrInfinite<'a>;
pub type String = css_parse::T![String];
pub type Number = css_parse::T![Number];
pub type Uri = crate::Url;
pub type ClipSource = crate::Url;
pub type MaskSource = crate::Url;
pub type BgImage<'a> = crate::NoneOr<crate::Image<'a>>;
/// `<content-replacement>` = `<image>` per css-content-3 spec.
pub type ContentReplacement<'a> = crate::Image<'a>;
