[workspace]
resolver = "2"
members = ["crates/*"]
exclude = ["packages/csskit_zed"]

[workspace.package]
authors = ["Keith Cirkel (https://keithcirkel.co.uk)"]
description = "Refreshing CSS!"
edition = "2024"
homepage = "https://hdx.rs"
keywords = ["CSS", "parser"]
license = "MIT"
repository = "https://github.com/csskit/csskit"

[workspace.dependencies]
# Local packages
csskit = { version = "0.0.1", path = "crates/csskit" }
csskit_derives = { version = "0.0.0", path = "crates/csskit_derives" }
csskit_proc_macro = { version = "0.0.0", path = "crates/csskit_proc_macro" }
css_parse = { version = "0.0.1", path = "crates/css_parse" }
css_lexer = { version = "0.0.1", path = "crates/css_lexer" }
css_ast = { version = "0.0.0", path = "crates/css_ast" }
csskit_source_finder = { version = "0.0.0", path = "crates/csskit_source_finder" }
csskit_transform = { version = "0.0.0", path = "crates/csskit_transform" }
csskit_highlight = { version = "0.0.0", path = "crates/csskit_highlight" }
csskit_lsp = { version = "0.0.0", path = "crates/csskit_lsp" }

# Memory
bumpalo = { version = "3.19.0" }

# Data structure libraries/helpers
bitmask-enum = { version = "2.2.5" }
itertools = { version = "0.14.0" }
ropey = { version = "1.6.1" }
smallvec = { version = "1.15.1" }
strum = { version = "0.27.2" }
phf = { version = "0.12.1" }

# CLI
clap = { version = "4.5.42" }
glob = { version = "0.3.2" }
project-root = { version = "0.2.2" }

# LSP packages
lsp-types = { version = "0.97.0" }
httparse = { version = "1.10.1" }

# Multithreading
crossbeam-channel = { version = "0.5.13" }
dashmap = { version = "6.1.0" }

# Logging
tracing = { version = "0.1.41" }
tracing-subscriber = { version = "0.3.19" }
console = { version = "0.16.0" }

# Error handling
miette = { version = "7.6.0", default-features = false }
thiserror = { version = "2.0.12" }

# Procc Macro Tools
syn = { version = "2.0.104" }
quote = { version = "1.0.40" }
proc-macro2 = { version = "1.0.95" }
heck = { version = "0.5.0" }

# Serialization
serde = { version = "1.0.219" }
serde_json = { version = "1.0.141" }

# Testing, benchmarking
similar = { version = "2.7.0" }
criterion = { version = "0.5.1" }     # Held back for pprof (https://github.com/tikv/pprof-rs/pull/271)
pprof = { version = "0.15.0" }
flate2 = { version = "1.1.2" }
insta = { version = "1.43.1" }
prettyplease = { version = "0.2.36" }

# String interning
string_cache = { version = "0.8.9" }
string_cache_codegen = { version = "0.5.4" }

# Build tools
grep-regex = { version = "0.1.13" }
grep-matcher = { version = "0.1.7" }
grep-searcher = { version = "0.1.14" }

# Wasm
wasm-bindgen = { version = "0.2.100" }
serde-wasm-bindgen = { version = "0.6.5" }
console_error_panic_hook = { version = "0.1.7" }

[workspace.metadata.workspaces]
allow_branch = "main"

[profile.release]
# Configurations explicitly listed here for clarity.
# Using the best options for performance.
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "symbols"
debug = false
panic = "abort"   # Let it crash and force ourselves to write safe Rust.

# Use the `--profile release-debug` flag to show symbols in release mode.
# e.g. `cargo build --profile release-debug`
[profile.release-debug]
inherits = "release"
strip = false
debug = true

# For faster compiles during development, opt-level some dynamic libraries
[profile.dev.package]
criterion.opt-level = 3
insta.opt-level = 3
similar.opt-level = 3
