[workspace]
resolver = "2"
members = ["crates/*", "tasks/*"]

[workspace.package]
authors = ["Keith Cirkel <hdx@keithcirkel.co.uk>"]
description = "Refreshing CSS!"
edition = "2021"
homepage = "https://github.com/keithamus/hdx"
keywords = ["CSS", "parser"]
license = "MIT"
repository = "https://github.com/keithamus/hdx"

[workspace.dependencies]
hdx = { version = "0.0.1", path = "crates/hdx" }
hdx_atom = { version = "0.0.0", path = "crates/hdx_atom" }
hdx_derive = { version = "0.0.0", path = "crates/hdx_derive" }
hdx_parser = { version = "0.0.1", path = "crates/hdx_parser" }
hdx_lexer = { version = "0.0.1", path = "crates/hdx_lexer" }
hdx_syntax = { version = "0.0.0", path = "crates/hdx_syntax" }
hdx_ast = { version = "0.0.0", path = "crates/hdx_ast" }
hdx_writer = { version = "0.0.0", path = "crates/hdx_writer" }

# Use OXC Allocator until https://github.com/fitzgen/bumpalo/pull/210 is resolved
oxc_allocator = { version = "0.6.0" }

bumpalo = { version = "3.13.0" }

clap = { version = "4.3.19" }

closestmatch = { version = "0.1.2" }
miette = { version = "6.0.1" }
thiserror = { version = "1.0.43" }
serde = { version = "1.0.171" }
serde_json = { version = "1.0.102" }
syn = { version = "2.0.26" }
quote = { version = "1.0.31" }
proc-macro2 = { version = "1.0.66" }
bitmask-enum = { version = "2.2.1" }

glob = { version = "0.3.1" }
pico-args = { version = "0.5.0" }
project-root = { version = "0.2.2" }
similar = { version = "2.2.1" }
criterion = { version = "0.5.1" }

string_cache = { version = "0.8.7" }
string_cache_codegen = { version = "0.5.2" }

grep-regex = { version = "0.1.11" }
grep-matcher = { version = "0.1.6" }
grep-searcher = { version = "0.1.11" }

[workspace.metadata.workspaces]
allow_branch = "main"

[profile.release]
# Configurations explicitly listed here for clarity.
# Using the best options for performance.
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "symbols"
debug = false
panic = "abort"   # Let it crash and force ourselves to write safe Rust.

# Use the `--profile release-debug` flag to show symbols in release mode.
# e.g. `cargo build --profile release-debug`
[profile.release-debug]
inherits = "release"
strip = false
debug = true
