version = "Two"

# Make Rust more readable given most people have wide screens nowadays.
# This is also the setting used by [rustc](https://github.com/rust-lang/rust/blob/master/rustfmt.toml)
use_small_heuristics = "Max"

# Use field initialize shorthand if possible
use_field_init_shorthand = true

# Supported by nightly Rust
unstable_features = true

# Provide a cleaner import sort order
group_imports = "StdExternalCrate"

# Provide a cleaner impl order
reorder_impl_items = true

# Group "use" statements by crate
imports_granularity = "Crate"

# Use tab for alignment
hard_tabs = true

# Hard stop line length at 120 chars
max_width = 120

# Make comments a little more like prose and have them block to 80 chars
comment_width = 80
wrap_comments = true
