# Properties that should be commented out because their parsing rules are tricky.
# Once we figure out how to parse them in csskit_proc_macro/src/def.rs, we can
# remove them from this file and the generator will uncomment them.

[variables]
properties = ["--*"]
