// AUTO-GENERATED from w3c/csswg-drafts
// Commit: https://github.com/w3c/csswg-drafts/commit/dfe6fb4ae983a5ed16fa628992e5a5e6188e6dcd
// Do not edit this file directly.
#![allow(warnings)]
//! https://drafts.csswg.org/css-color-hdr-1/

mod impls;
use super::prelude::*;
use impls::*;
/// Represents the style value for `dynamic-range-limit` as defined in [css-color-hdr-1](https://drafts.csswg.org/css-color-hdr-1/#dynamic-range-limit).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// standard | no-limit | constrained | <dynamic-range-limit-mix()>
/// ```
///
/// https://drafts.csswg.org/css-color-hdr-1/#dynamic-range-limit
#[syntax(" standard | no-limit | constrained | <dynamic-range-limit-mix()> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "no-limit",
    inherits,
    applies_to = Elements,
    animation_type = Unknown,
    property_group = ColorHdr,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.dynamic-range-limit"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub enum DynamicRangeLimitStyleValue<'a> {}
