// AUTO-GENERATED from w3c/csswg-drafts
// Commit: https://github.com/w3c/csswg-drafts/commit/c68df4265b71c6c1f927d42d76868cded8e931be
// Do not edit this file directly.
#![allow(warnings)]
//! https://drafts.csswg.org/css-overscroll-1/

mod impls;
use super::prelude::*;
use impls::*;
/// Represents the style value for `overscroll-behavior` as defined in [css-overscroll-1](https://drafts.csswg.org/css-overscroll-1/#overscroll-behavior).
///
/// The overscroll-behavior CSS property disables default scrolling behaviors when the edges of a scrolling area are reached.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// [ contain | none | auto ]{1,2}
/// ```
///
/// https://drafts.csswg.org/css-overscroll-1/#overscroll-behavior
#[syntax(" [ contain | none | auto ]{1,2} ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto auto",
    applies_to = Unknown,
    animation_type = Discrete,
    longhands = OverscrollBehaviorX|OverscrollBehaviorY,
    property_group = Overscroll,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.overscroll-behavior"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct OverscrollBehaviorStyleValue;

/// Represents the style value for `overscroll-behavior-block` as defined in [css-overscroll-1](https://drafts.csswg.org/css-overscroll-1/#overscroll-behavior-block).
///
/// The overscroll-behavior CSS property disables default scrolling behaviors when the edges of a scrolling area are reached.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// contain | none | auto
/// ```
///
/// https://drafts.csswg.org/css-overscroll-1/#overscroll-behavior-block
#[syntax(" contain | none | auto ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = Discrete,
    property_group = Overscroll,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
    logical_property_group = OverscrollBehavior,
    box_side = BlockStart|BlockEnd,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.overscroll-behavior-block"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub enum OverscrollBehaviorBlockStyleValue {}

/// Represents the style value for `overscroll-behavior-inline` as defined in [css-overscroll-1](https://drafts.csswg.org/css-overscroll-1/#overscroll-behavior-inline).
///
/// The overscroll-behavior CSS property disables default scrolling behaviors when the edges of a scrolling area are reached.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// contain | none | auto
/// ```
///
/// https://drafts.csswg.org/css-overscroll-1/#overscroll-behavior-inline
#[syntax(" contain | none | auto ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = Discrete,
    property_group = Overscroll,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
    logical_property_group = OverscrollBehavior,
    box_side = InlineStart|InlineEnd,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(
	feature = "css_feature_data",
	derive(ToCSSFeature),
	css_feature("css.properties.overscroll-behavior-inline")
)]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub enum OverscrollBehaviorInlineStyleValue {}

/// Represents the style value for `overscroll-behavior-x` as defined in [css-overscroll-1](https://drafts.csswg.org/css-overscroll-1/#overscroll-behavior-x).
///
/// The overscroll-behavior CSS property disables default scrolling behaviors when the edges of a scrolling area are reached.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// contain | none | auto
/// ```
///
/// https://drafts.csswg.org/css-overscroll-1/#overscroll-behavior-x
#[syntax(" contain | none | auto ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = Discrete,
    shorthand_group = OverscrollBehavior,
    property_group = Overscroll,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
    logical_property_group = OverscrollBehavior,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.overscroll-behavior-x"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub enum OverscrollBehaviorXStyleValue {}

/// Represents the style value for `overscroll-behavior-y` as defined in [css-overscroll-1](https://drafts.csswg.org/css-overscroll-1/#overscroll-behavior-y).
///
/// The overscroll-behavior CSS property disables default scrolling behaviors when the edges of a scrolling area are reached.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// contain | none | auto
/// ```
///
/// https://drafts.csswg.org/css-overscroll-1/#overscroll-behavior-y
#[syntax(" contain | none | auto ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = Discrete,
    shorthand_group = OverscrollBehavior,
    property_group = Overscroll,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
    logical_property_group = OverscrollBehavior,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.overscroll-behavior-y"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub enum OverscrollBehaviorYStyleValue {}
