// AUTO-GENERATED from w3c/csswg-drafts
// Commit: https://github.com/w3c/csswg-drafts/commit/81c50fcb76c30cbffe6af36484531dfc153abe88
// Do not edit this file directly.
#![allow(warnings)]
//! https://drafts.csswg.org/css-sizing-4/

mod impls;
use super::prelude::*;
use impls::*;
/// Represents the style value for `aspect-ratio` as defined in [css-sizing-4](https://drafts.csswg.org/css-sizing-4/#aspect-ratio).
///
/// The aspect-ratio CSS property controls the width-to-height ratio of elements. For <img> and <video> elements, the width and height attributes used together with height: auto control the aspect ratio while the image/video is loading.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto || <ratio>
/// ```
///
/// https://drafts.csswg.org/css-sizing-4/#aspect-ratio
#[syntax(" auto || <ratio> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    property_group = Sizing,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.aspect-ratio"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
#[derive(csskit_derives::NodeWithMetadata)]
pub struct AspectRatioStyleValue<'a>;

/// Represents the style value for `block-size` as defined in [css-sizing-4](https://drafts.csswg.org/css-sizing-4/#block-size).
///
/// CSS logical properties control borders, size, margin, and padding with directions and dimensions relative to the writing mode. For example, in a left to right, top to bottom writing mode, block-end refers to the bottom. Also known as flow relative.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | <box-size>
/// ```
///
/// https://drafts.csswg.org/css-sizing-4/#block-size
#[syntax(" auto | <box-size> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    percentages = ContainingBlock,
    property_group = Sizing,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
    logical_property_group = Size,
    box_portion = Size,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.block-size"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
#[derive(csskit_derives::NodeWithMetadata)]
pub struct BlockSizeStyleValue<'a>;

/// Represents the style value for `box-sizing` as defined in [css-sizing-4](https://drafts.csswg.org/css-sizing-4/#box-sizing).
///
/// The box-sizing CSS property sets whether an element's width and height are calculated based on the content-box, which does not count the size of borders or padding, or border-box, which does count them.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// content-box | border-box
/// ```
///
/// https://drafts.csswg.org/css-sizing-4/#box-sizing
#[syntax(" content-box | border-box ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "content-box",
    applies_to = Unknown,
    animation_type = Discrete,
    property_group = Sizing,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.box-sizing"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
#[derive(csskit_derives::NodeWithMetadata)]
pub enum BoxSizingStyleValue<'a> {}

/// Represents the style value for `contain-intrinsic-block-size` as defined in [css-sizing-4](https://drafts.csswg.org/css-sizing-4/#contain-intrinsic-block-size).
///
/// The contain-intrinsic-size CSS property sets the intrinsic size of an element. When using size containment, the browser will lay out the element as if it had a single child of this size.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto? [ none | <length [0,∞]> ]
/// ```
///
/// https://drafts.csswg.org/css-sizing-4/#contain-intrinsic-block-size
#[syntax(" auto? [ none | <length [0,∞]> ] ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "none",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    property_group = Sizing,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
    logical_property_group = ContainIntrinsicSize,
    box_side = BlockStart|BlockEnd,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(
	feature = "css_feature_data",
	derive(ToCSSFeature),
	css_feature("css.properties.contain-intrinsic-block-size")
)]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
#[derive(csskit_derives::NodeWithMetadata)]
pub struct ContainIntrinsicBlockSizeStyleValue<'a>;

/// Represents the style value for `contain-intrinsic-height` as defined in [css-sizing-4](https://drafts.csswg.org/css-sizing-4/#contain-intrinsic-height).
///
/// The contain-intrinsic-size CSS property sets the intrinsic size of an element. When using size containment, the browser will lay out the element as if it had a single child of this size.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto? [ none | <length [0,∞]> ]
/// ```
///
/// https://drafts.csswg.org/css-sizing-4/#contain-intrinsic-height
#[syntax(" auto? [ none | <length [0,∞]> ] ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "none",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    shorthands = ContainIntrinsicSize,
    property_group = Sizing,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
    logical_property_group = ContainIntrinsicSize,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.contain-intrinsic-height"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
#[derive(csskit_derives::NodeWithMetadata)]
pub struct ContainIntrinsicHeightStyleValue<'a>;

/// Represents the style value for `contain-intrinsic-inline-size` as defined in [css-sizing-4](https://drafts.csswg.org/css-sizing-4/#contain-intrinsic-inline-size).
///
/// The contain-intrinsic-size CSS property sets the intrinsic size of an element. When using size containment, the browser will lay out the element as if it had a single child of this size.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto? [ none | <length [0,∞]> ]
/// ```
///
/// https://drafts.csswg.org/css-sizing-4/#contain-intrinsic-inline-size
#[syntax(" auto? [ none | <length [0,∞]> ] ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "none",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    property_group = Sizing,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
    logical_property_group = ContainIntrinsicSize,
    box_side = InlineStart|InlineEnd,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(
	feature = "css_feature_data",
	derive(ToCSSFeature),
	css_feature("css.properties.contain-intrinsic-inline-size")
)]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
#[derive(csskit_derives::NodeWithMetadata)]
pub struct ContainIntrinsicInlineSizeStyleValue<'a>;

/// Represents the style value for `contain-intrinsic-size` as defined in [css-sizing-4](https://drafts.csswg.org/css-sizing-4/#contain-intrinsic-size).
///
/// The contain-intrinsic-size CSS property sets the intrinsic size of an element. When using size containment, the browser will lay out the element as if it had a single child of this size.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// [ auto? [ none | <length [0,∞]> ] ]{1,2}
/// ```
///
/// https://drafts.csswg.org/css-sizing-4/#contain-intrinsic-size
#[syntax(" [ auto? [ none | <length [0,∞]> ] ]{1,2} ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "see individual properties",
    inherits = Unknown,
    applies_to = Unknown,
    animation_type = Unknown,
    percentages = Unknown,
    longhands = ContainIntrinsicWidth|ContainIntrinsicHeight,
    property_group = Sizing,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[declaration_writes(repeat)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.contain-intrinsic-size"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
#[derive(csskit_derives::NodeWithMetadata)]
pub struct ContainIntrinsicSizeStyleValue<'a>;

/// Represents the style value for `contain-intrinsic-width` as defined in [css-sizing-4](https://drafts.csswg.org/css-sizing-4/#contain-intrinsic-width).
///
/// The contain-intrinsic-size CSS property sets the intrinsic size of an element. When using size containment, the browser will lay out the element as if it had a single child of this size.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto? [ none | <length [0,∞]> ]
/// ```
///
/// https://drafts.csswg.org/css-sizing-4/#contain-intrinsic-width
#[syntax(" auto? [ none | <length [0,∞]> ] ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "none",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    shorthands = ContainIntrinsicSize,
    property_group = Sizing,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
    logical_property_group = ContainIntrinsicSize,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.contain-intrinsic-width"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
#[derive(csskit_derives::NodeWithMetadata)]
pub struct ContainIntrinsicWidthStyleValue<'a>;

/// Represents the style value for `frame-sizing` as defined in [css-sizing-4](https://drafts.csswg.org/css-sizing-4/#frame-sizing).
///
/// The frame-sizing CSS property sets the size of an <iframe> element to that of it contents, to avoid scrolling in the iframe. Embedded documents allow this with the <meta name="responsive-embedded-sizing"> element and request resizing in the embedding page by calling window.requestResize().
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | content-width | content-height | content-block-size | content-inline-size
/// ```
///
/// https://drafts.csswg.org/css-sizing-4/#frame-sizing
#[syntax(" auto | content-width | content-height | content-block-size | content-inline-size ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = Discrete,
    property_group = Sizing,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.frame-sizing"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
#[derive(csskit_derives::NodeWithMetadata)]
pub enum FrameSizingStyleValue<'a> {}

/// Represents the style value for `height` as defined in [css-sizing-4](https://drafts.csswg.org/css-sizing-4/#height).
///
/// The width and height CSS properties set the preferred physical size of an element.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | <box-size> | stretch | fit-content | contain | -webkit-max-content | -moz-max-content | -webkit-min-content | -moz-min-content
/// ```
///
/// https://drafts.csswg.org/css-sizing-4/#height
#[syntax(
	" auto | <box-size> | stretch | fit-content | contain | -webkit-max-content | -moz-max-content | -webkit-min-content | -moz-min-content "
)]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    percentages = ContainingBlock,
    property_group = Sizing,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
    logical_property_group = Size,
    box_portion = Size,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.height"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
#[derive(csskit_derives::NodeWithMetadata)]
pub enum HeightStyleValue<'a> {}

/// Represents the style value for `inline-size` as defined in [css-sizing-4](https://drafts.csswg.org/css-sizing-4/#inline-size).
///
/// CSS logical properties control borders, size, margin, and padding with directions and dimensions relative to the writing mode. For example, in a left to right, top to bottom writing mode, block-end refers to the bottom. Also known as flow relative.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | <box-size>
/// ```
///
/// https://drafts.csswg.org/css-sizing-4/#inline-size
#[syntax(" auto | <box-size> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    percentages = ContainingBlock,
    property_group = Sizing,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
    logical_property_group = Size,
    box_portion = Size,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.inline-size"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
#[derive(csskit_derives::NodeWithMetadata)]
pub struct InlineSizeStyleValue<'a>;

/// Represents the style value for `max-block-size` as defined in [css-sizing-4](https://drafts.csswg.org/css-sizing-4/#max-block-size).
///
/// CSS logical properties control borders, size, margin, and padding with directions and dimensions relative to the writing mode. For example, in a left to right, top to bottom writing mode, block-end refers to the bottom. Also known as flow relative.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// none | <box-size>
/// ```
///
/// https://drafts.csswg.org/css-sizing-4/#max-block-size
#[syntax(" none | <box-size> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "none",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    percentages = ContainingBlock,
    property_group = Sizing,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
    logical_property_group = MaxSize,
    box_side = BlockStart|BlockEnd,
    box_portion = Size,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.max-block-size"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
#[derive(csskit_derives::NodeWithMetadata)]
pub struct MaxBlockSizeStyleValue<'a>;

/// Represents the style value for `max-height` as defined in [css-sizing-4](https://drafts.csswg.org/css-sizing-4/#max-height).
///
/// The min-width, min-height, max-width, and max-height CSS properties set the minimum and maximum size of an element.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// none | <box-size> | stretch | fit-content | contain | -webkit-max-content | -moz-max-content | -webkit-min-content | -moz-min-content
/// ```
///
/// https://drafts.csswg.org/css-sizing-4/#max-height
#[syntax(
	" none | <box-size> | stretch | fit-content | contain | -webkit-max-content | -moz-max-content | -webkit-min-content | -moz-min-content "
)]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "none",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    percentages = ContainingBlock,
    property_group = Sizing,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
    logical_property_group = MaxSize,
    box_portion = Size,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.max-height"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
#[derive(csskit_derives::NodeWithMetadata)]
pub enum MaxHeightStyleValue<'a> {}

/// Represents the style value for `max-inline-size` as defined in [css-sizing-4](https://drafts.csswg.org/css-sizing-4/#max-inline-size).
///
/// CSS logical properties control borders, size, margin, and padding with directions and dimensions relative to the writing mode. For example, in a left to right, top to bottom writing mode, block-end refers to the bottom. Also known as flow relative.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// none | <box-size>
/// ```
///
/// https://drafts.csswg.org/css-sizing-4/#max-inline-size
#[syntax(" none | <box-size> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "none",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    percentages = ContainingBlock,
    property_group = Sizing,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
    logical_property_group = MaxSize,
    box_side = InlineStart|InlineEnd,
    box_portion = Size,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.max-inline-size"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
#[derive(csskit_derives::NodeWithMetadata)]
pub struct MaxInlineSizeStyleValue<'a>;

/// Represents the style value for `max-size` as defined in [css-sizing-4](https://drafts.csswg.org/css-sizing-4/#max-size).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <'max-width'> <'max-height'>?
/// ```
///
/// https://drafts.csswg.org/css-sizing-4/#max-size
#[syntax(" <'max-width'> <'max-height'>? ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "none",
    inherits = Unknown,
    applies_to = Elements,
    animation_type = Unknown,
    percentages = Unknown,
    property_group = Sizing,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.max-size"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
#[derive(csskit_derives::NodeWithMetadata)]
pub struct MaxSizeStyleValue<'a>;

/// Represents the style value for `max-width` as defined in [css-sizing-4](https://drafts.csswg.org/css-sizing-4/#max-width).
///
/// The min-width, min-height, max-width, and max-height CSS properties set the minimum and maximum size of an element.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// none | <box-size> | stretch | fit-content | contain | -webkit-max-content | -moz-max-content | -webkit-min-content | -moz-min-content
/// ```
///
/// https://drafts.csswg.org/css-sizing-4/#max-width
#[syntax(
	" none | <box-size> | stretch | fit-content | contain | -webkit-max-content | -moz-max-content | -webkit-min-content | -moz-min-content "
)]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "none",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    percentages = ContainingBlock,
    property_group = Sizing,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
    logical_property_group = MaxSize,
    box_portion = Size,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.max-width"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
#[derive(csskit_derives::NodeWithMetadata)]
pub enum MaxWidthStyleValue<'a> {}

/// Represents the style value for `min-block-size` as defined in [css-sizing-4](https://drafts.csswg.org/css-sizing-4/#min-block-size).
///
/// CSS logical properties control borders, size, margin, and padding with directions and dimensions relative to the writing mode. For example, in a left to right, top to bottom writing mode, block-end refers to the bottom. Also known as flow relative.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | <box-size>
/// ```
///
/// https://drafts.csswg.org/css-sizing-4/#min-block-size
#[syntax(" auto | <box-size> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    percentages = ContainingBlock,
    property_group = Sizing,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
    logical_property_group = MinSize,
    box_side = BlockStart|BlockEnd,
    box_portion = Size,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.min-block-size"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
#[derive(csskit_derives::NodeWithMetadata)]
pub struct MinBlockSizeStyleValue<'a>;

/// Represents the style value for `min-height` as defined in [css-sizing-4](https://drafts.csswg.org/css-sizing-4/#min-height).
///
/// The min-width, min-height, max-width, and max-height CSS properties set the minimum and maximum size of an element.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | <box-size> | stretch | fit-content | contain | -webkit-max-content | -moz-max-content | -webkit-min-content | -moz-min-content
/// ```
///
/// https://drafts.csswg.org/css-sizing-4/#min-height
#[syntax(
	" auto | <box-size> | stretch | fit-content | contain | -webkit-max-content | -moz-max-content | -webkit-min-content | -moz-min-content "
)]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    percentages = ContainingBlock,
    property_group = Sizing,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
    logical_property_group = MinSize,
    box_portion = Size,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.min-height"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
#[derive(csskit_derives::NodeWithMetadata)]
pub enum MinHeightStyleValue<'a> {}

/// Represents the style value for `min-inline-size` as defined in [css-sizing-4](https://drafts.csswg.org/css-sizing-4/#min-inline-size).
///
/// CSS logical properties control borders, size, margin, and padding with directions and dimensions relative to the writing mode. For example, in a left to right, top to bottom writing mode, block-end refers to the bottom. Also known as flow relative.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | <box-size>
/// ```
///
/// https://drafts.csswg.org/css-sizing-4/#min-inline-size
#[syntax(" auto | <box-size> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    percentages = ContainingBlock,
    property_group = Sizing,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
    logical_property_group = MinSize,
    box_side = InlineStart|InlineEnd,
    box_portion = Size,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.min-inline-size"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
#[derive(csskit_derives::NodeWithMetadata)]
pub struct MinInlineSizeStyleValue<'a>;

/// Represents the style value for `min-intrinsic-sizing` as defined in [css-sizing-4](https://drafts.csswg.org/css-sizing-4/#min-intrinsic-sizing).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// legacy | zero-if-scroll || zero-if-extrinsic
/// ```
///
/// https://drafts.csswg.org/css-sizing-4/#min-intrinsic-sizing
#[syntax(" legacy | zero-if-scroll || zero-if-extrinsic ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "legacy",
    applies_to = Unknown,
    animation_type = Discrete,
    property_group = Sizing,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.min-intrinsic-sizing"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
#[derive(csskit_derives::NodeWithMetadata)]
pub enum MinIntrinsicSizingStyleValue<'a> {}

/// Represents the style value for `min-size` as defined in [css-sizing-4](https://drafts.csswg.org/css-sizing-4/#min-size).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <'min-width'> <'min-height'>?
/// ```
///
/// https://drafts.csswg.org/css-sizing-4/#min-size
#[syntax(" <'min-width'> <'min-height'>? ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    inherits = Unknown,
    applies_to = Elements,
    animation_type = Unknown,
    percentages = Unknown,
    property_group = Sizing,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.min-size"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
#[derive(csskit_derives::NodeWithMetadata)]
pub struct MinSizeStyleValue<'a>;

/// Represents the style value for `min-width` as defined in [css-sizing-4](https://drafts.csswg.org/css-sizing-4/#min-width).
///
/// The min-width, min-height, max-width, and max-height CSS properties set the minimum and maximum size of an element.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | <box-size> | stretch | fit-content | contain | -webkit-max-content | -moz-max-content | -webkit-min-content | -moz-min-content
/// ```
///
/// https://drafts.csswg.org/css-sizing-4/#min-width
#[syntax(
	" auto | <box-size> | stretch | fit-content | contain | -webkit-max-content | -moz-max-content | -webkit-min-content | -moz-min-content "
)]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    percentages = ContainingBlock,
    property_group = Sizing,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
    logical_property_group = MinSize,
    box_portion = Size,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.min-width"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
#[derive(csskit_derives::NodeWithMetadata)]
pub enum MinWidthStyleValue<'a> {}

/// Represents the style value for `size` as defined in [css-sizing-4](https://drafts.csswg.org/css-sizing-4/#size).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <'width'> <'height'>?
/// ```
///
/// https://drafts.csswg.org/css-sizing-4/#size
#[syntax(" <'width'> <'height'>? ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    inherits = Unknown,
    applies_to = Elements,
    animation_type = Unknown,
    percentages = Unknown,
    property_group = Sizing,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.size"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
#[derive(csskit_derives::NodeWithMetadata)]
pub struct SizeStyleValue<'a>;

/// Represents the style value for `width` as defined in [css-sizing-4](https://drafts.csswg.org/css-sizing-4/#width).
///
/// The width and height CSS properties set the preferred physical size of an element.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | <box-size> | stretch | fit-content | contain | -webkit-max-content | -moz-max-content | -webkit-min-content | -moz-min-content
/// ```
///
/// https://drafts.csswg.org/css-sizing-4/#width
#[syntax(
	" auto | <box-size> | stretch | fit-content | contain | -webkit-max-content | -moz-max-content | -webkit-min-content | -moz-min-content "
)]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    percentages = ContainingBlock,
    property_group = Sizing,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
    logical_property_group = Size,
    box_portion = Size,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.width"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
#[derive(csskit_derives::NodeWithMetadata)]
pub enum WidthStyleValue<'a> {}
