// AUTO-GENERATED from w3c/csswg-drafts
// Commit: https://github.com/w3c/csswg-drafts/commit/7292c6d8ff9e9f062af880c4a74bafa29577cd79
// Do not edit this file directly.
#![allow(warnings)]
//! https://drafts.csswg.org/css-line-grid-1/

mod impls;
use super::prelude::*;
use impls::*;
/// Represents the style value for `box-snap` as defined in [css-line-grid-1](https://drafts.csswg.org/css-line-grid-1/#box-snap).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// none | block-start | block-end | center | baseline | last-baseline
/// ```
///
/// https://drafts.csswg.org/css-line-grid-1/#box-snap
#[syntax(" none | block-start | block-end | center | baseline | last-baseline ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "none",
    inherits,
    applies_to = Unknown,
    animation_type = Discrete,
    property_group = LineGrid,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.box-snap"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub enum BoxSnapStyleValue {}

/// Represents the style value for `line-grid` as defined in [css-line-grid-1](https://drafts.csswg.org/css-line-grid-1/#line-grid).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// match-parent | create
/// ```
///
/// https://drafts.csswg.org/css-line-grid-1/#line-grid
#[syntax(" match-parent | create ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "match-parent",
    applies_to = Unknown,
    animation_type = Discrete,
    property_group = LineGrid,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.line-grid"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub enum LineGridStyleValue {}

/// Represents the style value for `line-snap` as defined in [css-line-grid-1](https://drafts.csswg.org/css-line-grid-1/#line-snap).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// none | baseline | contain
/// ```
///
/// https://drafts.csswg.org/css-line-grid-1/#line-snap
#[syntax(" none | baseline | contain ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "none",
    inherits,
    applies_to = Block,
    animation_type = Discrete,
    property_group = LineGrid,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.line-snap"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub enum LineSnapStyleValue {}
