// AUTO-GENERATED from w3c/csswg-drafts
// Commit: https://github.com/w3c/csswg-drafts/commit/5ca249fead116718a90d071caa68ecc5c9f9134f
// Do not edit this file directly.
#![allow(warnings)]
//! https://drafts.csswg.org/css-image-animation-1/

mod impls;
use super::prelude::*;
use impls::*;
/// Represents the style value for `image-animation` as defined in [css-image-animation-1](https://drafts.csswg.org/css-image-animation-1/#image-animation).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// normal | paused | running
/// ```
///
/// https://drafts.csswg.org/css-image-animation-1/#image-animation
#[syntax(" normal | paused | running ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "normal",
    inherits,
    applies_to = Unknown,
    animation_type = Discrete,
    property_group = ImageAnimation,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.image-animation"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
#[derive(csskit_derives::NodeWithMetadata)]
pub enum ImageAnimationStyleValue {}
