// AUTO-GENERATED from w3c/csswg-drafts
// Commit: https://github.com/w3c/csswg-drafts/commit/dfe6fb4ae983a5ed16fa628992e5a5e6188e6dcd
// Do not edit this file directly.
#![allow(warnings)]
//! https://drafts.csswg.org/css-gaps-1/

mod impls;
use super::prelude::*;
use impls::*;
/// Represents the style value for `column-rule` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#column-rule).
///
/// Multi-column layout flows an element's content across one or more columns in a single row, without affecting the display property of its children.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <gap-rule-list> | <gap-auto-rule-list>
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#column-rule
#[syntax(" <gap-rule-list> | <gap-auto-rule-list> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "see individual properties",
    inherits = Unknown,
    applies_to = Unknown,
    animation_type = Unknown,
    percentages = Unknown,
    longhands = ColumnRuleColor|ColumnRuleStyle|ColumnRuleWidth,
    property_group = Gaps,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.column-rule"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub enum ColumnRuleStyleValue {}

/// Represents the style value for `column-rule-break` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#column-rule-break).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// none | spanning-item | intersection
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#column-rule-break
#[syntax(" none | spanning-item | intersection ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "spanning-item",
    applies_to = Unknown,
    animation_type = Discrete,
    property_group = Gaps,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.column-rule-break"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub enum ColumnRuleBreakStyleValue {}

/// Represents the style value for `column-rule-color` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#column-rule-color).
///
/// Multi-column layout flows an element's content across one or more columns in a single row, without affecting the display property of its children.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <line-color-list> | <auto-line-color-list>
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#column-rule-color
#[syntax(" <line-color-list> | <auto-line-color-list> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "currentcolor",
    applies_to = Unknown,
    animation_type = RepeatableList,
    shorthand_group = ColumnRule,
    property_group = Gaps,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.column-rule-color"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub enum ColumnRuleColorStyleValue {}

/// Represents the style value for `column-rule-edge-inset` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#column-rule-edge-inset).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <length-percentage> [ <length-percentage> ]?
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#column-rule-edge-inset
#[syntax(" <length-percentage> [ <length-percentage> ]? ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "see individual properties",
    inherits = Unknown,
    applies_to = Unknown,
    animation_type = Unknown,
    percentages = Unknown,
    property_group = Gaps,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.column-rule-edge-inset"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct ColumnRuleEdgeInsetStyleValue;

/// Represents the style value for `column-rule-edge-inset-end` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#column-rule-edge-inset-end).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | <length-percentage>
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#column-rule-edge-inset-end
#[syntax(" auto | <length-percentage> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    percentages = Unknown,
    property_group = Gaps,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(
	feature = "css_feature_data",
	derive(ToCSSFeature),
	css_feature("css.properties.column-rule-edge-inset-end")
)]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct ColumnRuleEdgeInsetEndStyleValue;

/// Represents the style value for `column-rule-edge-inset-start` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#column-rule-edge-inset-start).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | <length-percentage>
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#column-rule-edge-inset-start
#[syntax(" auto | <length-percentage> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    percentages = Unknown,
    property_group = Gaps,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(
	feature = "css_feature_data",
	derive(ToCSSFeature),
	css_feature("css.properties.column-rule-edge-inset-start")
)]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct ColumnRuleEdgeInsetStartStyleValue;

/// Represents the style value for `column-rule-inset` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#column-rule-inset).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <length-percentage> <length-percentage>? [/ <length-percentage> <length-percentage>?]?
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#column-rule-inset
#[syntax(" <length-percentage> <length-percentage>? [/ <length-percentage> <length-percentage>?]? ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "see individual properties",
    inherits = Unknown,
    applies_to = Unknown,
    animation_type = Unknown,
    percentages = Unknown,
    property_group = Gaps,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.column-rule-inset"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct ColumnRuleInsetStyleValue;

/// Represents the style value for `column-rule-inset-end` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#column-rule-inset-end).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | <length-percentage>
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#column-rule-inset-end
#[syntax(" auto | <length-percentage> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "see individual properties",
    inherits = Unknown,
    applies_to = Unknown,
    animation_type = Unknown,
    percentages = Unknown,
    property_group = Gaps,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.column-rule-inset-end"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct ColumnRuleInsetEndStyleValue;

/// Represents the style value for `column-rule-inset-start` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#column-rule-inset-start).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | <length-percentage>
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#column-rule-inset-start
#[syntax(" auto | <length-percentage> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "see individual properties",
    inherits = Unknown,
    applies_to = Unknown,
    animation_type = Unknown,
    percentages = Unknown,
    property_group = Gaps,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.column-rule-inset-start"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct ColumnRuleInsetStartStyleValue;

/// Represents the style value for `column-rule-interior-inset` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#column-rule-interior-inset).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <length-percentage> [ <length-percentage> ]?
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#column-rule-interior-inset
#[syntax(" <length-percentage> [ <length-percentage> ]? ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "see individual properties",
    inherits = Unknown,
    applies_to = Unknown,
    animation_type = Unknown,
    percentages = Unknown,
    property_group = Gaps,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(
	feature = "css_feature_data",
	derive(ToCSSFeature),
	css_feature("css.properties.column-rule-interior-inset")
)]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct ColumnRuleInteriorInsetStyleValue;

/// Represents the style value for `column-rule-interior-inset-end` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#column-rule-interior-inset-end).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | <length-percentage>
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#column-rule-interior-inset-end
#[syntax(" auto | <length-percentage> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    percentages = Unknown,
    property_group = Gaps,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(
	feature = "css_feature_data",
	derive(ToCSSFeature),
	css_feature("css.properties.column-rule-interior-inset-end")
)]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct ColumnRuleInteriorInsetEndStyleValue;

/// Represents the style value for `column-rule-interior-inset-start` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#column-rule-interior-inset-start).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | <length-percentage>
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#column-rule-interior-inset-start
#[syntax(" auto | <length-percentage> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    percentages = Unknown,
    property_group = Gaps,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(
	feature = "css_feature_data",
	derive(ToCSSFeature),
	css_feature("css.properties.column-rule-interior-inset-start")
)]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct ColumnRuleInteriorInsetStartStyleValue;

/// Represents the style value for `column-rule-style` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#column-rule-style).
///
/// Multi-column layout flows an element's content across one or more columns in a single row, without affecting the display property of its children.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <line-style-list> | <auto-line-style-list>
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#column-rule-style
#[syntax(" <line-style-list> | <auto-line-style-list> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "none",
    applies_to = Unknown,
    animation_type = Discrete,
    shorthand_group = ColumnRule,
    property_group = Gaps,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.column-rule-style"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub enum ColumnRuleStyleStyleValue {}

/// Represents the style value for `column-rule-width` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#column-rule-width).
///
/// Multi-column layout flows an element's content across one or more columns in a single row, without affecting the display property of its children.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <line-width-list> | <auto-line-width-list>
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#column-rule-width
#[syntax(" <line-width-list> | <auto-line-width-list> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "medium",
    applies_to = Unknown,
    animation_type = RepeatableList,
    shorthand_group = ColumnRule,
    property_group = Gaps,
    computed_value_type = ListOfAbsoluteLengths,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.column-rule-width"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub enum ColumnRuleWidthStyleValue<'a> {}

/// Represents the style value for `row-rule` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#row-rule).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <gap-rule-list> | <gap-auto-rule-list>
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#row-rule
#[syntax(" <gap-rule-list> | <gap-auto-rule-list> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "see individual properties",
    inherits = Unknown,
    applies_to = Unknown,
    animation_type = Unknown,
    percentages = Unknown,
    property_group = Gaps,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.row-rule"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub enum RowRuleStyleValue {}

/// Represents the style value for `row-rule-break` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#row-rule-break).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// none | spanning-item | intersection
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#row-rule-break
#[syntax(" none | spanning-item | intersection ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "spanning-item",
    applies_to = Unknown,
    animation_type = Discrete,
    property_group = Gaps,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.row-rule-break"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub enum RowRuleBreakStyleValue {}

/// Represents the style value for `row-rule-color` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#row-rule-color).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <line-color-list> | <auto-line-color-list>
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#row-rule-color
#[syntax(" <line-color-list> | <auto-line-color-list> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "currentcolor",
    applies_to = Unknown,
    animation_type = RepeatableList,
    property_group = Gaps,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.row-rule-color"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub enum RowRuleColorStyleValue {}

/// Represents the style value for `row-rule-edge-inset` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#row-rule-edge-inset).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <length-percentage> [ <length-percentage> ]?
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#row-rule-edge-inset
#[syntax(" <length-percentage> [ <length-percentage> ]? ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "see individual properties",
    inherits = Unknown,
    applies_to = Unknown,
    animation_type = Unknown,
    percentages = Unknown,
    property_group = Gaps,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.row-rule-edge-inset"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct RowRuleEdgeInsetStyleValue;

/// Represents the style value for `row-rule-edge-inset-end` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#row-rule-edge-inset-end).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | <length-percentage>
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#row-rule-edge-inset-end
#[syntax(" auto | <length-percentage> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    percentages = Unknown,
    property_group = Gaps,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.row-rule-edge-inset-end"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct RowRuleEdgeInsetEndStyleValue;

/// Represents the style value for `row-rule-edge-inset-start` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#row-rule-edge-inset-start).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | <length-percentage>
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#row-rule-edge-inset-start
#[syntax(" auto | <length-percentage> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    percentages = Unknown,
    property_group = Gaps,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.row-rule-edge-inset-start"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct RowRuleEdgeInsetStartStyleValue;

/// Represents the style value for `row-rule-inset` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#row-rule-inset).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <length-percentage> <length-percentage>? [/ <length-percentage> <length-percentage>?]?
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#row-rule-inset
#[syntax(" <length-percentage> <length-percentage>? [/ <length-percentage> <length-percentage>?]? ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "see individual properties",
    inherits = Unknown,
    applies_to = Unknown,
    animation_type = Unknown,
    percentages = Unknown,
    property_group = Gaps,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.row-rule-inset"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct RowRuleInsetStyleValue;

/// Represents the style value for `row-rule-inset-end` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#row-rule-inset-end).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | <length-percentage>
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#row-rule-inset-end
#[syntax(" auto | <length-percentage> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "see individual properties",
    inherits = Unknown,
    applies_to = Unknown,
    animation_type = Unknown,
    percentages = Unknown,
    property_group = Gaps,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.row-rule-inset-end"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct RowRuleInsetEndStyleValue;

/// Represents the style value for `row-rule-inset-start` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#row-rule-inset-start).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | <length-percentage>
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#row-rule-inset-start
#[syntax(" auto | <length-percentage> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "see individual properties",
    inherits = Unknown,
    applies_to = Unknown,
    animation_type = Unknown,
    percentages = Unknown,
    property_group = Gaps,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.row-rule-inset-start"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct RowRuleInsetStartStyleValue;

/// Represents the style value for `row-rule-interior-inset` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#row-rule-interior-inset).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <length-percentage> [ <length-percentage> ]?
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#row-rule-interior-inset
#[syntax(" <length-percentage> [ <length-percentage> ]? ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "see individual properties",
    inherits = Unknown,
    applies_to = Unknown,
    animation_type = Unknown,
    percentages = Unknown,
    property_group = Gaps,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.row-rule-interior-inset"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct RowRuleInteriorInsetStyleValue;

/// Represents the style value for `row-rule-interior-inset-end` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#row-rule-interior-inset-end).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | <length-percentage>
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#row-rule-interior-inset-end
#[syntax(" auto | <length-percentage> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    percentages = Unknown,
    property_group = Gaps,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(
	feature = "css_feature_data",
	derive(ToCSSFeature),
	css_feature("css.properties.row-rule-interior-inset-end")
)]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct RowRuleInteriorInsetEndStyleValue;

/// Represents the style value for `row-rule-interior-inset-start` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#row-rule-interior-inset-start).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | <length-percentage>
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#row-rule-interior-inset-start
#[syntax(" auto | <length-percentage> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    percentages = Unknown,
    property_group = Gaps,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(
	feature = "css_feature_data",
	derive(ToCSSFeature),
	css_feature("css.properties.row-rule-interior-inset-start")
)]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct RowRuleInteriorInsetStartStyleValue;

/// Represents the style value for `row-rule-style` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#row-rule-style).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <line-style-list> | <auto-line-style-list>
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#row-rule-style
#[syntax(" <line-style-list> | <auto-line-style-list> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "none",
    applies_to = Unknown,
    animation_type = Discrete,
    property_group = Gaps,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.row-rule-style"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub enum RowRuleStyleStyleValue {}

/// Represents the style value for `row-rule-width` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#row-rule-width).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <line-width-list> | <auto-line-width-list>
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#row-rule-width
#[syntax(" <line-width-list> | <auto-line-width-list> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "medium",
    applies_to = Unknown,
    animation_type = RepeatableList,
    property_group = Gaps,
    computed_value_type = ListOfAbsoluteLengths,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.row-rule-width"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub enum RowRuleWidthStyleValue<'a> {}

/// Represents the style value for `rule` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#rule).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <'column-rule'>
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#rule
#[syntax(" <'column-rule'> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "see individual properties",
    applies_to = Unknown,
    animation_type = Unknown,
    percentages = Unknown,
    property_group = Gaps,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.rule"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct RuleStyleValue;

/// Represents the style value for `rule-break` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#rule-break).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <'column-rule-break'>
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#rule-break
#[syntax(" <'column-rule-break'> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "see individual properties",
    inherits = Unknown,
    applies_to = Unknown,
    animation_type = Unknown,
    percentages = Unknown,
    property_group = Gaps,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.rule-break"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct RuleBreakStyleValue;

/// Represents the style value for `rule-color` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#rule-color).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <'column-rule-color'>
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#rule-color
#[syntax(" <'column-rule-color'> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "see individual properties",
    applies_to = Unknown,
    animation_type = Unknown,
    percentages = Unknown,
    property_group = Gaps,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.rule-color"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct RuleColorStyleValue;

/// Represents the style value for `rule-edge-inset` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#rule-edge-inset).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <'column-rule-edge-inset'>
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#rule-edge-inset
#[syntax(" <'column-rule-edge-inset'> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "see individual properties",
    inherits = Unknown,
    applies_to = Unknown,
    animation_type = Unknown,
    percentages = Unknown,
    property_group = Gaps,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.rule-edge-inset"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct RuleEdgeInsetStyleValue;

/// Represents the style value for `rule-inset` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#rule-inset).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <'column-rule-inset'>
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#rule-inset
#[syntax(" <'column-rule-inset'> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "see individual properties",
    inherits = Unknown,
    applies_to = Unknown,
    animation_type = Unknown,
    percentages = Unknown,
    property_group = Gaps,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.rule-inset"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct RuleInsetStyleValue;

/// Represents the style value for `rule-inset-end` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#rule-inset-end).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <'column-rule-inset-end'>
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#rule-inset-end
#[syntax(" <'column-rule-inset-end'> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "see individual properties",
    inherits = Unknown,
    applies_to = Unknown,
    animation_type = Unknown,
    percentages = Unknown,
    property_group = Gaps,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.rule-inset-end"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct RuleInsetEndStyleValue;

/// Represents the style value for `rule-inset-start` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#rule-inset-start).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <'column-rule-inset-start'>
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#rule-inset-start
#[syntax(" <'column-rule-inset-start'> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "see individual properties",
    inherits = Unknown,
    applies_to = Unknown,
    animation_type = Unknown,
    percentages = Unknown,
    property_group = Gaps,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.rule-inset-start"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct RuleInsetStartStyleValue;

/// Represents the style value for `rule-interior-inset` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#rule-interior-inset).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <'column-rule-interior-inset'>
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#rule-interior-inset
#[syntax(" <'column-rule-interior-inset'> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "see individual properties",
    inherits = Unknown,
    applies_to = Unknown,
    animation_type = Unknown,
    percentages = Unknown,
    property_group = Gaps,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.rule-interior-inset"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct RuleInteriorInsetStyleValue;

/// Represents the style value for `rule-overlap` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#rule-overlap).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// row-over-column | column-over-row
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#rule-overlap
#[syntax(" row-over-column | column-over-row ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "row-over-column",
    applies_to = Unknown,
    animation_type = Discrete,
    property_group = Gaps,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.rule-overlap"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub enum RuleOverlapStyleValue {}

/// Represents the style value for `rule-style` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#rule-style).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <'column-rule-style'>
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#rule-style
#[syntax(" <'column-rule-style'> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "see individual properties",
    applies_to = Unknown,
    animation_type = Unknown,
    percentages = Unknown,
    property_group = Gaps,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.rule-style"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct RuleStyleStyleValue;

/// Represents the style value for `rule-width` as defined in [css-gaps-1](https://drafts.csswg.org/css-gaps-1/#rule-width).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <'column-rule-width'>
/// ```
///
/// https://drafts.csswg.org/css-gaps-1/#rule-width
#[syntax(" <'column-rule-width'> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "see individual properties",
    applies_to = Unknown,
    animation_type = Unknown,
    percentages = Unknown,
    property_group = Gaps,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.rule-width"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct RuleWidthStyleValue<'a>;
