// AUTO-GENERATED - Do not edit this file directly.
#![allow(warnings)]
//! https://w3c.github.io/pointerevents/

mod impls;
use super::prelude::*;
use impls::*;
/// Represents the style value for `touch-action` as defined in [Pointer Events](https://w3c.github.io/pointerevents/#touch-action).
///
/// The touch-action CSS property sets whether an element on a touch screen can be panned or pinched to zoom.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | none | [ [ pan-x | pan-left | pan-right ] || [ pan-y | pan-up | pan-down ] || pinch-zoom ] | manipulation
/// ```
///
/// https://w3c.github.io/pointerevents/#touch-action
#[syntax(
	" auto | none | [ [ pan-x | pan-left | pan-right ] || [ pan-y | pan-up | pan-down ] || pinch-zoom ] | manipulation "
)]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    property_group = PointerEvents,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.touch-action"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
#[derive(csskit_derives::NodeWithMetadata)]
pub enum TouchActionStyleValue {}
