// AUTO-GENERATED from w3c/csswg-drafts
// Commit: https://github.com/w3c/csswg-drafts/commit/7e27ad7484307dfdbe9d0e18ad19d02859389688
// Do not edit this file directly.
#![allow(warnings)]
//! https://drafts.csswg.org/css-round-display-1/

mod impls;
use super::prelude::*;
use impls::*;
/// Represents the style value for `border-boundary` as defined in [css-round-display-1](https://drafts.csswg.org/css-round-display-1/#border-boundary).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// none | parent | display
/// ```
///
/// https://drafts.csswg.org/css-round-display-1/#border-boundary
#[syntax(" none | parent | display ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "none",
    inherits,
    applies_to = Elements,
    animation_type = Discrete,
    property_group = RoundDisplay,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
    box_portion = Border,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.border-boundary"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
#[derive(csskit_derives::NodeWithMetadata)]
pub enum BorderBoundaryStyleValue {}
