// AUTO-GENERATED from w3c/csswg-drafts
// Commit: https://github.com/w3c/csswg-drafts/commit/4401d6101f52bec41fe998fdc46c417453e10b61
// Do not edit this file directly.
#![allow(warnings)]
//! https://drafts.csswg.org/css-content-3/

mod impls;
use super::prelude::*;
use impls::*;
/// Represents the style value for `bookmark-label` as defined in [css-content-3](https://drafts.csswg.org/css-content-3/#bookmark-label).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <content-list>
/// ```
///
/// https://drafts.csswg.org/css-content-3/#bookmark-label
#[syntax(" <content-list> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "content(text)",
    applies_to = Elements,
    animation_type = Discrete,
    property_group = Content,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.bookmark-label"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct BookmarkLabelStyleValue<'a>;

/// Represents the style value for `bookmark-level` as defined in [css-content-3](https://drafts.csswg.org/css-content-3/#bookmark-level).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// none | <integer [1,∞]>
/// ```
///
/// https://drafts.csswg.org/css-content-3/#bookmark-level
#[syntax(" none | <integer [1,∞]> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "none",
    applies_to = Elements,
    animation_type = ByComputedValue,
    property_group = Content,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.bookmark-level"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct BookmarkLevelStyleValue;

/// Represents the style value for `bookmark-state` as defined in [css-content-3](https://drafts.csswg.org/css-content-3/#bookmark-state).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// open | closed
/// ```
///
/// https://drafts.csswg.org/css-content-3/#bookmark-state
#[syntax(" open | closed ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "open",
    applies_to = Block,
    animation_type = Discrete,
    property_group = Content,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.bookmark-state"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub enum BookmarkStateStyleValue {}

// /// Represents the style value for `content` as defined in [css-content-3](https://drafts.csswg.org/css-content-3/#content).
// ///
// /// The content CSS property sets the content inside of an element or pseudo-element, replacing the current value. It's often used with the ::before and ::after pseudo-elements to generate cosmetic content.
// ///
// /// The grammar is defined as:
// ///
// /// ```text,ignore
// /// normal | none | [ <content-replacement> | <content-list> ] [/ [ <string> | <counter> | <attr()> ]+ ]?
// /// ```
// ///
// /// https://drafts.csswg.org/css-content-3/#content
// #[syntax(
//     " normal | none | [ <content-replacement> | <content-list> ] [/ [ <string> | <counter> | <attr()> ]+ ]? "
// )]
// #[derive(
//     Parse,
//     Peek,
//     ToSpan,
//     ToCursors,
//     DeclarationMetadata,
//     SemanticEq,
//     Debug,
//     Clone,
//     PartialEq,
//     Eq,
//     PartialOrd,
//     Ord,
//     Hash,
// )]
// #[declaration_metadata(
//     initial = "normal",
//     applies_to = Unknown,
//     animation_type = Discrete,
//     property_group = Content,
//     computed_value_type = Unknown,
//     canonical_order = "per grammar",
// )]
// #[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
// #[cfg_attr(
//     feature = "css_feature_data",
//     derive(ToCSSFeature),
//     css_feature("css.properties.content")
// )]
// #[cfg_attr(feature = "visitable", derive(Visitable), visit)]
// pub enum ContentStyleValue<'a> {}

// /// Represents the style value for `quotes` as defined in [css-content-3](https://drafts.csswg.org/css-content-3/#quotes).
// ///
// /// The quotes CSS property sets the quotation marks inserted via the content CSS property or <q> element.
// ///
// /// The grammar is defined as:
// ///
// /// ```text,ignore
// /// auto | none | match-parent | [ <string> <string> ]+
// /// ```
// ///
// /// https://drafts.csswg.org/css-content-3/#quotes
// #[syntax(" auto | none | match-parent | [ <string> <string> ]+ ")]
// #[derive(
//     Parse,
//     Peek,
//     ToSpan,
//     ToCursors,
//     DeclarationMetadata,
//     SemanticEq,
//     Debug,
//     Clone,
//     PartialEq,
//     Eq,
//     PartialOrd,
//     Ord,
//     Hash,
// )]
// #[declaration_metadata(
//     initial = "auto",
//     inherits,
//     applies_to = Elements,
//     animation_type = Discrete,
//     property_group = Content,
//     computed_value_type = Unknown,
//     canonical_order = "per grammar",
// )]
// #[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
// #[cfg_attr(
//     feature = "css_feature_data",
//     derive(ToCSSFeature),
//     css_feature("css.properties.quotes")
// )]
// #[cfg_attr(feature = "visitable", derive(Visitable), visit)]
// pub enum QuotesStyleValue<'a> {}
