[package]
name = "csskit-fuzz"
version = "0.0.0"
edition = "2024"
publish = false

[package.metadata]
cargo-fuzz = true

[workspace]

[[bin]]
doc = false
name = "parse_stylesheet"
path = "fuzz_targets/parse_stylesheet.rs"
test = false

[dependencies]
bumpalo = { version = "3.20.3" }
css_ast = { path = "../crates/css_ast" }
css_lexer = { path = "../crates/css_lexer" }
css_parse = { path = "../crates/css_parse" }
libfuzzer-sys = "0.4.13"
