// AUTO-GENERATED from w3c/csswg-drafts
// Commit: https://github.com/w3c/csswg-drafts/commit/ddbceaa3cee88f134d557c3051c26fcb5554a535
// Do not edit this file directly.
#![allow(warnings)]
//! https://drafts.csswg.org/css-variables-2/

mod impls;
use super::prelude::*;
use impls::*;
