// AUTO-GENERATED from w3c/csswg-drafts
// Commit: https://github.com/w3c/csswg-drafts/commit/33682af340a2c61ce7e632f0b4d3bde01a3a27de
// Do not edit this file directly.
#![allow(warnings)]
//! https://drafts.csswg.org/css-variables-2/

mod impls;
use super::prelude::*;
use impls::*;
