// AUTO-GENERATED from w3c/csswg-drafts
// Commit: https://github.com/w3c/csswg-drafts/commit/58eb9b3f45e73a3e4ae51b253a25fa2a11ad142c
// Do not edit this file directly.
#![allow(warnings)]
//! https://drafts.csswg.org/css-variables-2/

mod impls;
use super::prelude::*;
use impls::*;
