// AUTO-GENERATED from w3c/csswg-drafts
// Commit: https://github.com/w3c/csswg-drafts/commit/4838deeea6c063e9a351226bd0e8f11c189cae37
// Do not edit this file directly.
#![allow(warnings)]
//! https://drafts.csswg.org/css-values-5/

mod impls;
use super::prelude::*;
use impls::*;
/// Represents the style value for `interpolate-size` as defined in [css-values-5](https://drafts.csswg.org/css-values-5/#interpolate-size).
///
/// The interpolate-size CSS property sets whether animations and transitions interpolate between a numeric value and a keyword value, such as from a fixed length to auto or fit-content.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// numeric-only | allow-keywords
/// ```
///
/// https://drafts.csswg.org/css-values-5/#interpolate-size
#[syntax(" numeric-only | allow-keywords ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "numeric-only",
    inherits,
    applies_to = Elements,
    property_group = Values,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.interpolate-size"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub enum InterpolateSizeStyleValue {}
