// AUTO-GENERATED from w3c/csswg-drafts
// Commit: https://github.com/w3c/csswg-drafts/commit/c68df4265b71c6c1f927d42d76868cded8e931be
// Do not edit this file directly.
#![allow(warnings)]
//! https://drafts.csswg.org/css-regions-1/

mod impls;
use super::prelude::*;
use impls::*;
/// Represents the style value for `flow-from` as defined in [css-regions-1](https://drafts.csswg.org/css-regions-1/#flow-from).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <custom-ident> | none
/// ```
///
/// https://drafts.csswg.org/css-regions-1/#flow-from
#[syntax(" <custom-ident> | none ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "none",
    applies_to = Unknown,
    property_group = Regions,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.flow-from"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct FlowFromStyleValue;

// /// Represents the style value for `flow-into` as defined in [css-regions-1](https://drafts.csswg.org/css-regions-1/#flow-into).
// ///
// /// The grammar is defined as:
// ///
// /// ```text,ignore
// /// none | <custom-ident> [element | content]?
// /// ```
// ///
// /// https://drafts.csswg.org/css-regions-1/#flow-into
// #[syntax(" none | <custom-ident> [element | content]? ")]
// #[derive(
//     Parse,
//     Peek,
//     ToSpan,
//     ToCursors,
//     DeclarationMetadata,
//     SemanticEq,
//     Debug,
//     Clone,
//     PartialEq,
//     Eq,
//     PartialOrd,
//     Ord,
//     Hash,
// )]
// #[declaration_metadata(
//     initial = "none",
//     applies_to = Unknown,
//     property_group = Regions,
//     computed_value_type = AsSpecified,
//     canonical_order = "per grammar",
// )]
// #[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
// #[cfg_attr(
//     feature = "css_feature_data",
//     derive(ToCSSFeature),
//     css_feature("css.properties.flow-into")
// )]
// #[cfg_attr(feature = "visitable", derive(Visitable), visit)]
// pub struct FlowIntoStyleValue;

/// Represents the style value for `region-fragment` as defined in [css-regions-1](https://drafts.csswg.org/css-regions-1/#region-fragment).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | break
/// ```
///
/// https://drafts.csswg.org/css-regions-1/#region-fragment
#[syntax(" auto | break ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = Discrete,
    property_group = Regions,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.region-fragment"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub enum RegionFragmentStyleValue {}
