// AUTO-GENERATED from w3c/csswg-drafts
// Commit: https://github.com/w3c/csswg-drafts/commit/f5642b931d905128daa075fdfeba6c9e74475b5a
// Do not edit this file directly.
#![allow(warnings)]
//! https://drafts.csswg.org/css-shaders-1/

mod impls;
use super::prelude::*;
use impls::*;
