// AUTO-GENERATED from w3c/csswg-drafts
// Commit: https://github.com/w3c/csswg-drafts/commit/4838deeea6c063e9a351226bd0e8f11c189cae37
// Do not edit this file directly.
#![allow(warnings)]
//! https://drafts.csswg.org/css-shaders-1/

mod impls;
use super::prelude::*;
use impls::*;
