// AUTO-GENERATED from w3c/csswg-drafts
// Commit: https://github.com/w3c/csswg-drafts/commit/c5657c29b10b07011ea478337776a83317a129b4
// Do not edit this file directly.
#![allow(warnings)]
//! https://drafts.csswg.org/css-shaders-1/

mod impls;
use super::prelude::*;
use impls::*;
