// AUTO-GENERATED from w3c/csswg-drafts
// Commit: https://github.com/w3c/csswg-drafts/commit/dfe6fb4ae983a5ed16fa628992e5a5e6188e6dcd
// Do not edit this file directly.
#![allow(warnings)]
//! https://drafts.csswg.org/css-scroll-snap-2/

mod impls;
use super::prelude::*;
use impls::*;
/// Represents the style value for `scroll-initial-target` as defined in [css-scroll-snap-2](https://drafts.csswg.org/css-scroll-snap-2/#scroll-initial-target).
///
/// The scroll-initial-target: nearest CSS declaration sets the initial scroll position of its scroll container to the top of the element, much like scrolling to a URL fragment.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// none | nearest
/// ```
///
/// https://drafts.csswg.org/css-scroll-snap-2/#scroll-initial-target
#[syntax(" none | nearest ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "none",
    applies_to = Elements,
    property_group = ScrollSnap,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.scroll-initial-target"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub enum ScrollInitialTargetStyleValue {}

/// Represents the style value for `scroll-margin` as defined in [css-scroll-snap-2](https://drafts.csswg.org/css-scroll-snap-2/#scroll-margin).
///
/// CSS scroll snap controls the panning and scrolling behavior within a scroll container.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <length>{1,4}
/// ```
///
/// https://drafts.csswg.org/css-scroll-snap-2/#scroll-margin
#[syntax(" <length>{1,4} ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "0",
    applies_to = Elements,
    animation_type = ByComputedValue,
    longhands = ScrollMarginBottom|ScrollMarginLeft|ScrollMarginRight|ScrollMarginTop,
    property_group = ScrollSnap,
    computed_value_type = AbsoluteLength,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.scroll-margin"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct ScrollMarginStyleValue;

/// Represents the style value for `scroll-margin-block` as defined in [css-scroll-snap-2](https://drafts.csswg.org/css-scroll-snap-2/#scroll-margin-block).
///
/// CSS scroll snap controls the panning and scrolling behavior within a scroll container.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <length>{1,2}
/// ```
///
/// https://drafts.csswg.org/css-scroll-snap-2/#scroll-margin-block
#[syntax(" <length>{1,2} ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "0",
    applies_to = Elements,
    animation_type = ByComputedValue,
    longhands = ScrollMarginBlockEnd|ScrollMarginBlockStart,
    property_group = ScrollSnap,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
    box_side = BlockStart|BlockEnd,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.scroll-margin-block"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct ScrollMarginBlockStyleValue;

/// Represents the style value for `scroll-margin-block-end` as defined in [css-scroll-snap-2](https://drafts.csswg.org/css-scroll-snap-2/#scroll-margin-block-end).
///
/// CSS scroll snap controls the panning and scrolling behavior within a scroll container.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <length>
/// ```
///
/// https://drafts.csswg.org/css-scroll-snap-2/#scroll-margin-block-end
#[syntax(" <length> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "0",
    applies_to = Elements,
    animation_type = ByComputedValue,
    shorthand_group = ScrollMarginBlock,
    property_group = ScrollSnap,
    computed_value_type = AbsoluteLength,
    canonical_order = "per grammar",
    logical_property_group = ScrollMargin,
    box_side = BlockEnd,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.scroll-margin-block-end"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct ScrollMarginBlockEndStyleValue;

/// Represents the style value for `scroll-margin-block-start` as defined in [css-scroll-snap-2](https://drafts.csswg.org/css-scroll-snap-2/#scroll-margin-block-start).
///
/// CSS scroll snap controls the panning and scrolling behavior within a scroll container.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <length>
/// ```
///
/// https://drafts.csswg.org/css-scroll-snap-2/#scroll-margin-block-start
#[syntax(" <length> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "0",
    applies_to = Elements,
    animation_type = ByComputedValue,
    shorthand_group = ScrollMarginBlock,
    property_group = ScrollSnap,
    computed_value_type = AbsoluteLength,
    canonical_order = "per grammar",
    logical_property_group = ScrollMargin,
    box_side = BlockStart,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.scroll-margin-block-start"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct ScrollMarginBlockStartStyleValue;

/// Represents the style value for `scroll-margin-bottom` as defined in [css-scroll-snap-2](https://drafts.csswg.org/css-scroll-snap-2/#scroll-margin-bottom).
///
/// CSS scroll snap controls the panning and scrolling behavior within a scroll container.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <length>
/// ```
///
/// https://drafts.csswg.org/css-scroll-snap-2/#scroll-margin-bottom
#[syntax(" <length> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "0",
    applies_to = Elements,
    animation_type = ByComputedValue,
    shorthand_group = ScrollMargin,
    property_group = ScrollSnap,
    computed_value_type = AbsoluteLength,
    canonical_order = "per grammar",
    logical_property_group = ScrollMargin,
    box_side = Bottom,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.scroll-margin-bottom"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct ScrollMarginBottomStyleValue;

/// Represents the style value for `scroll-margin-inline` as defined in [css-scroll-snap-2](https://drafts.csswg.org/css-scroll-snap-2/#scroll-margin-inline).
///
/// CSS scroll snap controls the panning and scrolling behavior within a scroll container.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <length>{1,2}
/// ```
///
/// https://drafts.csswg.org/css-scroll-snap-2/#scroll-margin-inline
#[syntax(" <length>{1,2} ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "0",
    applies_to = Elements,
    animation_type = ByComputedValue,
    longhands = ScrollMarginInlineEnd|ScrollMarginInlineStart,
    property_group = ScrollSnap,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
    box_side = InlineStart|InlineEnd,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.scroll-margin-inline"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct ScrollMarginInlineStyleValue;

/// Represents the style value for `scroll-margin-inline-end` as defined in [css-scroll-snap-2](https://drafts.csswg.org/css-scroll-snap-2/#scroll-margin-inline-end).
///
/// CSS scroll snap controls the panning and scrolling behavior within a scroll container.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <length>
/// ```
///
/// https://drafts.csswg.org/css-scroll-snap-2/#scroll-margin-inline-end
#[syntax(" <length> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "0",
    applies_to = Elements,
    animation_type = ByComputedValue,
    shorthand_group = ScrollMarginInline,
    property_group = ScrollSnap,
    computed_value_type = AbsoluteLength,
    canonical_order = "per grammar",
    logical_property_group = ScrollMargin,
    box_side = InlineEnd,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.scroll-margin-inline-end"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct ScrollMarginInlineEndStyleValue;

/// Represents the style value for `scroll-margin-inline-start` as defined in [css-scroll-snap-2](https://drafts.csswg.org/css-scroll-snap-2/#scroll-margin-inline-start).
///
/// CSS scroll snap controls the panning and scrolling behavior within a scroll container.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <length>
/// ```
///
/// https://drafts.csswg.org/css-scroll-snap-2/#scroll-margin-inline-start
#[syntax(" <length> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "0",
    applies_to = Elements,
    animation_type = ByComputedValue,
    shorthand_group = ScrollMarginInline,
    property_group = ScrollSnap,
    computed_value_type = AbsoluteLength,
    canonical_order = "per grammar",
    logical_property_group = ScrollMargin,
    box_side = InlineStart,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(
	feature = "css_feature_data",
	derive(ToCSSFeature),
	css_feature("css.properties.scroll-margin-inline-start")
)]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct ScrollMarginInlineStartStyleValue;

/// Represents the style value for `scroll-margin-left` as defined in [css-scroll-snap-2](https://drafts.csswg.org/css-scroll-snap-2/#scroll-margin-left).
///
/// CSS scroll snap controls the panning and scrolling behavior within a scroll container.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <length>
/// ```
///
/// https://drafts.csswg.org/css-scroll-snap-2/#scroll-margin-left
#[syntax(" <length> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "0",
    applies_to = Elements,
    animation_type = ByComputedValue,
    shorthand_group = ScrollMargin,
    property_group = ScrollSnap,
    computed_value_type = AbsoluteLength,
    canonical_order = "per grammar",
    logical_property_group = ScrollMargin,
    box_side = Left,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.scroll-margin-left"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct ScrollMarginLeftStyleValue;

/// Represents the style value for `scroll-margin-right` as defined in [css-scroll-snap-2](https://drafts.csswg.org/css-scroll-snap-2/#scroll-margin-right).
///
/// CSS scroll snap controls the panning and scrolling behavior within a scroll container.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <length>
/// ```
///
/// https://drafts.csswg.org/css-scroll-snap-2/#scroll-margin-right
#[syntax(" <length> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "0",
    applies_to = Elements,
    animation_type = ByComputedValue,
    shorthand_group = ScrollMargin,
    property_group = ScrollSnap,
    computed_value_type = AbsoluteLength,
    canonical_order = "per grammar",
    logical_property_group = ScrollMargin,
    box_side = Right,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.scroll-margin-right"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct ScrollMarginRightStyleValue;

/// Represents the style value for `scroll-margin-top` as defined in [css-scroll-snap-2](https://drafts.csswg.org/css-scroll-snap-2/#scroll-margin-top).
///
/// CSS scroll snap controls the panning and scrolling behavior within a scroll container.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// <length>
/// ```
///
/// https://drafts.csswg.org/css-scroll-snap-2/#scroll-margin-top
#[syntax(" <length> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "0",
    applies_to = Elements,
    animation_type = ByComputedValue,
    shorthand_group = ScrollMargin,
    property_group = ScrollSnap,
    computed_value_type = AbsoluteLength,
    canonical_order = "per grammar",
    logical_property_group = ScrollMargin,
    box_side = Top,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.scroll-margin-top"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct ScrollMarginTopStyleValue;

/// Represents the style value for `scroll-padding` as defined in [css-scroll-snap-2](https://drafts.csswg.org/css-scroll-snap-2/#scroll-padding).
///
/// CSS scroll snap controls the panning and scrolling behavior within a scroll container.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// [ auto | <length-percentage [0,∞]> ]{1,4}
/// ```
///
/// https://drafts.csswg.org/css-scroll-snap-2/#scroll-padding
#[syntax(" [ auto | <length-percentage [0,∞]> ]{1,4} ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    percentages = Scrollport,
    longhands = ScrollPaddingBottom|ScrollPaddingLeft|ScrollPaddingRight|ScrollPaddingTop,
    property_group = ScrollSnap,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.scroll-padding"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct ScrollPaddingStyleValue;

/// Represents the style value for `scroll-padding-block` as defined in [css-scroll-snap-2](https://drafts.csswg.org/css-scroll-snap-2/#scroll-padding-block).
///
/// CSS scroll snap controls the panning and scrolling behavior within a scroll container.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// [ auto | <length-percentage [0,∞]> ]{1,2}
/// ```
///
/// https://drafts.csswg.org/css-scroll-snap-2/#scroll-padding-block
#[syntax(" [ auto | <length-percentage [0,∞]> ]{1,2} ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    percentages = Scrollport,
    longhands = ScrollPaddingBlockEnd|ScrollPaddingBlockStart,
    property_group = ScrollSnap,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
    box_side = BlockStart|BlockEnd,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.scroll-padding-block"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct ScrollPaddingBlockStyleValue;

/// Represents the style value for `scroll-padding-block-end` as defined in [css-scroll-snap-2](https://drafts.csswg.org/css-scroll-snap-2/#scroll-padding-block-end).
///
/// CSS scroll snap controls the panning and scrolling behavior within a scroll container.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | <length-percentage [0,∞]>
/// ```
///
/// https://drafts.csswg.org/css-scroll-snap-2/#scroll-padding-block-end
#[syntax(" auto | <length-percentage [0,∞]> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    percentages = Scrollport,
    shorthand_group = ScrollPaddingBlock,
    property_group = ScrollSnap,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
    logical_property_group = ScrollPadding,
    box_side = BlockEnd,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.scroll-padding-block-end"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct ScrollPaddingBlockEndStyleValue;

/// Represents the style value for `scroll-padding-block-start` as defined in [css-scroll-snap-2](https://drafts.csswg.org/css-scroll-snap-2/#scroll-padding-block-start).
///
/// CSS scroll snap controls the panning and scrolling behavior within a scroll container.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | <length-percentage [0,∞]>
/// ```
///
/// https://drafts.csswg.org/css-scroll-snap-2/#scroll-padding-block-start
#[syntax(" auto | <length-percentage [0,∞]> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    percentages = Scrollport,
    shorthand_group = ScrollPaddingBlock,
    property_group = ScrollSnap,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
    logical_property_group = ScrollPadding,
    box_side = BlockStart,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(
	feature = "css_feature_data",
	derive(ToCSSFeature),
	css_feature("css.properties.scroll-padding-block-start")
)]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct ScrollPaddingBlockStartStyleValue;

/// Represents the style value for `scroll-padding-bottom` as defined in [css-scroll-snap-2](https://drafts.csswg.org/css-scroll-snap-2/#scroll-padding-bottom).
///
/// CSS scroll snap controls the panning and scrolling behavior within a scroll container.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | <length-percentage [0,∞]>
/// ```
///
/// https://drafts.csswg.org/css-scroll-snap-2/#scroll-padding-bottom
#[syntax(" auto | <length-percentage [0,∞]> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    percentages = Scrollport,
    shorthand_group = ScrollPadding,
    property_group = ScrollSnap,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
    logical_property_group = ScrollPadding,
    box_side = Bottom,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.scroll-padding-bottom"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct ScrollPaddingBottomStyleValue;

/// Represents the style value for `scroll-padding-inline` as defined in [css-scroll-snap-2](https://drafts.csswg.org/css-scroll-snap-2/#scroll-padding-inline).
///
/// CSS scroll snap controls the panning and scrolling behavior within a scroll container.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// [ auto | <length-percentage [0,∞]> ]{1,2}
/// ```
///
/// https://drafts.csswg.org/css-scroll-snap-2/#scroll-padding-inline
#[syntax(" [ auto | <length-percentage [0,∞]> ]{1,2} ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    percentages = Scrollport,
    longhands = ScrollPaddingInlineEnd|ScrollPaddingInlineStart,
    property_group = ScrollSnap,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
    box_side = InlineStart|InlineEnd,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.scroll-padding-inline"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct ScrollPaddingInlineStyleValue;

/// Represents the style value for `scroll-padding-inline-end` as defined in [css-scroll-snap-2](https://drafts.csswg.org/css-scroll-snap-2/#scroll-padding-inline-end).
///
/// CSS scroll snap controls the panning and scrolling behavior within a scroll container.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | <length-percentage [0,∞]>
/// ```
///
/// https://drafts.csswg.org/css-scroll-snap-2/#scroll-padding-inline-end
#[syntax(" auto | <length-percentage [0,∞]> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    percentages = Scrollport,
    shorthand_group = ScrollPaddingInline,
    property_group = ScrollSnap,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
    logical_property_group = ScrollPadding,
    box_side = InlineEnd,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.scroll-padding-inline-end"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct ScrollPaddingInlineEndStyleValue;

/// Represents the style value for `scroll-padding-inline-start` as defined in [css-scroll-snap-2](https://drafts.csswg.org/css-scroll-snap-2/#scroll-padding-inline-start).
///
/// CSS scroll snap controls the panning and scrolling behavior within a scroll container.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | <length-percentage [0,∞]>
/// ```
///
/// https://drafts.csswg.org/css-scroll-snap-2/#scroll-padding-inline-start
#[syntax(" auto | <length-percentage [0,∞]> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    percentages = Scrollport,
    shorthand_group = ScrollPaddingInline,
    property_group = ScrollSnap,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
    logical_property_group = ScrollPadding,
    box_side = InlineStart,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(
	feature = "css_feature_data",
	derive(ToCSSFeature),
	css_feature("css.properties.scroll-padding-inline-start")
)]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct ScrollPaddingInlineStartStyleValue;

/// Represents the style value for `scroll-padding-left` as defined in [css-scroll-snap-2](https://drafts.csswg.org/css-scroll-snap-2/#scroll-padding-left).
///
/// CSS scroll snap controls the panning and scrolling behavior within a scroll container.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | <length-percentage [0,∞]>
/// ```
///
/// https://drafts.csswg.org/css-scroll-snap-2/#scroll-padding-left
#[syntax(" auto | <length-percentage [0,∞]> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    percentages = Scrollport,
    shorthand_group = ScrollPadding,
    property_group = ScrollSnap,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
    logical_property_group = ScrollPadding,
    box_side = Left,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.scroll-padding-left"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct ScrollPaddingLeftStyleValue;

/// Represents the style value for `scroll-padding-right` as defined in [css-scroll-snap-2](https://drafts.csswg.org/css-scroll-snap-2/#scroll-padding-right).
///
/// CSS scroll snap controls the panning and scrolling behavior within a scroll container.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | <length-percentage [0,∞]>
/// ```
///
/// https://drafts.csswg.org/css-scroll-snap-2/#scroll-padding-right
#[syntax(" auto | <length-percentage [0,∞]> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    percentages = Scrollport,
    shorthand_group = ScrollPadding,
    property_group = ScrollSnap,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
    logical_property_group = ScrollPadding,
    box_side = Right,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.scroll-padding-right"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct ScrollPaddingRightStyleValue;

/// Represents the style value for `scroll-padding-top` as defined in [css-scroll-snap-2](https://drafts.csswg.org/css-scroll-snap-2/#scroll-padding-top).
///
/// CSS scroll snap controls the panning and scrolling behavior within a scroll container.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | <length-percentage [0,∞]>
/// ```
///
/// https://drafts.csswg.org/css-scroll-snap-2/#scroll-padding-top
#[syntax(" auto | <length-percentage [0,∞]> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = ByComputedValue,
    percentages = Scrollport,
    shorthand_group = ScrollPadding,
    property_group = ScrollSnap,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
    logical_property_group = ScrollPadding,
    box_side = Top,
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.scroll-padding-top"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct ScrollPaddingTopStyleValue;

/// Represents the style value for `scroll-snap-align` as defined in [css-scroll-snap-2](https://drafts.csswg.org/css-scroll-snap-2/#scroll-snap-align).
///
/// CSS scroll snap controls the panning and scrolling behavior within a scroll container.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// [ none | start | end | center ]{1,2}
/// ```
///
/// https://drafts.csswg.org/css-scroll-snap-2/#scroll-snap-align
#[syntax(" [ none | start | end | center ]{1,2} ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "none",
    applies_to = Elements,
    animation_type = Discrete,
    property_group = ScrollSnap,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.scroll-snap-align"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct ScrollSnapAlignStyleValue;

/// Represents the style value for `scroll-snap-stop` as defined in [css-scroll-snap-2](https://drafts.csswg.org/css-scroll-snap-2/#scroll-snap-stop).
///
/// CSS scroll snap controls the panning and scrolling behavior within a scroll container.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// normal | always
/// ```
///
/// https://drafts.csswg.org/css-scroll-snap-2/#scroll-snap-stop
#[syntax(" normal | always ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "normal",
    applies_to = Elements,
    animation_type = Discrete,
    property_group = ScrollSnap,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.scroll-snap-stop"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub enum ScrollSnapStopStyleValue {}

// /// Represents the style value for `scroll-snap-type` as defined in [css-scroll-snap-2](https://drafts.csswg.org/css-scroll-snap-2/#scroll-snap-type).
// ///
// /// CSS scroll snap controls the panning and scrolling behavior within a scroll container.
// ///
// /// The grammar is defined as:
// ///
// /// ```text,ignore
// /// none | [ x | y | block | inline | both ] [ mandatory | proximity ]?
// /// ```
// ///
// /// https://drafts.csswg.org/css-scroll-snap-2/#scroll-snap-type
// #[syntax(" none | [ x | y | block | inline | both ] [ mandatory | proximity ]? ")]
// #[derive(
//     Parse,
//     Peek,
//     ToSpan,
//     ToCursors,
//     DeclarationMetadata,
//     SemanticEq,
//     Debug,
//     Clone,
//     PartialEq,
//     Eq,
//     PartialOrd,
//     Ord,
//     Hash,
// )]
// #[declaration_metadata(
//     initial = "none",
//     applies_to = Elements,
//     animation_type = Discrete,
//     property_group = ScrollSnap,
//     computed_value_type = Unknown,
//     canonical_order = "per grammar",
// )]
// #[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
// #[cfg_attr(
//     feature = "css_feature_data",
//     derive(ToCSSFeature),
//     css_feature("css.properties.scroll-snap-type")
// )]
// #[cfg_attr(feature = "visitable", derive(Visitable), visit)]
// pub struct ScrollSnapTypeStyleValue;
