// AUTO-GENERATED from w3c/csswg-drafts
// Commit: https://github.com/w3c/csswg-drafts/commit/87009810995126409565d64617b3b447cf5b263f
// Do not edit this file directly.
#![allow(warnings)]
//! https://drafts.csswg.org/css-exclusions-1/

mod impls;
use super::prelude::*;
use impls::*;
/// Represents the style value for `wrap-flow` as defined in [css-exclusions-1](https://drafts.csswg.org/css-exclusions-1/#wrap-flow).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | both | start | end | minimum | maximum | clear
/// ```
///
/// https://drafts.csswg.org/css-exclusions-1/#wrap-flow
#[syntax(" auto | both | start | end | minimum | maximum | clear ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = Discrete,
    property_group = Exclusions,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.wrap-flow"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
#[derive(csskit_derives::NodeWithMetadata)]
pub enum WrapFlowStyleValue {}

/// Represents the style value for `wrap-through` as defined in [css-exclusions-1](https://drafts.csswg.org/css-exclusions-1/#wrap-through).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// wrap | none
/// ```
///
/// https://drafts.csswg.org/css-exclusions-1/#wrap-through
#[syntax(" wrap | none ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "wrap",
    applies_to = Block,
    animation_type = Discrete,
    property_group = Exclusions,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.wrap-through"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
#[derive(csskit_derives::NodeWithMetadata)]
pub enum WrapThroughStyleValue {}
