[package]
name = "css_parse"
version.workspace = true
authors.workspace = true
description = "A recursive-descent CSS parser with generic cursor sinks and rich diagnostics."
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
exclude = ["tests/*", "bench/*"]

[lints.rust]
warnings = { level = "deny", priority = -1 }

[lib]
bench = false

[dependencies]
csskit_proc_macro = { workspace = true }
css_lexer = { workspace = true }
csskit_arena = { workspace = true, features = ["collections"] }
source_tools = { workspace = true, features = ["csskit_arena"] }

allocator-api2 = { workspace = true }
smallvec = { workspace = true }

miette = { workspace = true, features = ["derive"], optional = true }
thiserror = { workspace = true, optional = true }
bitmask-enum = { workspace = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
stable_type_layout = { workspace = true }

[dev-dependencies]
csskit_derives = { workspace = true }
derive_atom_set = { workspace = true }
insta = { workspace = true }
glob = { workspace = true }
dhat = { workspace = true }

[features]
default = []
testing = []
# Easter egg feature for CSS expansion (opposite of minification)
egg = ["css_lexer/egg"]
miette = ["dep:miette", "dep:thiserror", "css_lexer/miette"]
serde = ["dep:serde", "dep:serde_json", "css_lexer/serde", "csskit_arena/serde"]
fancy = ["miette", "miette/fancy-no-backtrace"]
# Test only features
_dhat-heap-testing = []
