// AUTO-GENERATED from w3c/csswg-drafts
// Commit: https://github.com/w3c/csswg-drafts/commit/dfe6fb4ae983a5ed16fa628992e5a5e6188e6dcd
// Do not edit this file directly.
#![allow(warnings)]
//! https://drafts.csswg.org/css-page-4/

mod impls;
use super::prelude::*;
use impls::*;
/// Represents the style value for `page` as defined in [css-page-4](https://drafts.csswg.org/css-page-4/#page).
///
/// The @page CSS at-rule sets the page-specific dimensions and margins for content such as printed documents, ebooks, or slides.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | <custom-ident>
/// ```
///
/// https://drafts.csswg.org/css-page-4/#page
#[syntax(" auto | <custom-ident> ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = Discrete,
    property_group = Page,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.page"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub struct PageStyleValue;
