// AUTO-GENERATED from w3c/csswg-drafts
// Commit: https://github.com/w3c/csswg-drafts/commit/4838deeea6c063e9a351226bd0e8f11c189cae37
// Do not edit this file directly.
#![allow(warnings)]
//! https://drafts.csswg.org/css-ruby-1/

mod impls;
use super::prelude::*;
use impls::*;
/// Represents the style value for `ruby-align` as defined in [css-ruby-1](https://drafts.csswg.org/css-ruby-1/#ruby-align).
///
/// The ruby-align CSS property sets the spacing and alignment of ruby annotation text when it does not fill its available space.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// start | center | space-between | space-around
/// ```
///
/// https://drafts.csswg.org/css-ruby-1/#ruby-align
#[syntax(" start | center | space-between | space-around ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "space-around",
    inherits,
    applies_to = Unknown,
    animation_type = ByComputedValue,
    property_group = Ruby,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.ruby-align"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub enum RubyAlignStyleValue {}

/// Represents the style value for `ruby-merge` as defined in [css-ruby-1](https://drafts.csswg.org/css-ruby-1/#ruby-merge).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// separate | merge | auto
/// ```
///
/// https://drafts.csswg.org/css-ruby-1/#ruby-merge
#[syntax(" separate | merge | auto ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "separate",
    inherits,
    applies_to = Unknown,
    animation_type = ByComputedValue,
    property_group = Ruby,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.ruby-merge"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub enum RubyMergeStyleValue {}

/// Represents the style value for `ruby-overhang` as defined in [css-ruby-1](https://drafts.csswg.org/css-ruby-1/#ruby-overhang).
///
/// The ruby-overhang CSS property sets whether ruby annotations may overlap adjacent text.
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | none
/// ```
///
/// https://drafts.csswg.org/css-ruby-1/#ruby-overhang
#[syntax(" auto | none ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    inherits,
    applies_to = Unknown,
    animation_type = ByComputedValue,
    property_group = Ruby,
    computed_value_type = Unknown,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.ruby-overhang"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub enum RubyOverhangStyleValue {}

// /// Represents the style value for `ruby-position` as defined in [css-ruby-1](https://drafts.csswg.org/css-ruby-1/#ruby-position).
// ///
// /// The ruby-position CSS property sets the position of a ruby annotation in relation to its base text. Annotations can display over, under, or interleaved with the base text.
// ///
// /// The grammar is defined as:
// ///
// /// ```text,ignore
// /// [ alternate || [ over | under ] ] | inter-character
// /// ```
// ///
// /// https://drafts.csswg.org/css-ruby-1/#ruby-position
// #[syntax(" [ alternate || [ over | under ] ] | inter-character ")]
// #[derive(
//     Parse,
//     Peek,
//     ToSpan,
//     ToCursors,
//     DeclarationMetadata,
//     SemanticEq,
//     Debug,
//     Clone,
//     PartialEq,
//     Eq,
//     PartialOrd,
//     Ord,
//     Hash,
// )]
// #[declaration_metadata(
//     initial = "alternate",
//     inherits,
//     applies_to = Unknown,
//     animation_type = Discrete,
//     property_group = Ruby,
//     computed_value_type = Unknown,
//     canonical_order = "per grammar",
// )]
// #[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
// #[cfg_attr(
//     feature = "css_feature_data",
//     derive(ToCSSFeature),
//     css_feature("css.properties.ruby-position")
// )]
// #[cfg_attr(feature = "visitable", derive(Visitable), visit)]
// pub enum RubyPositionStyleValue {}
