use css_parse::keyword_set;

keyword_set!(pub enum NamedColor {
	Aliceblue: "aliceblue",
	Antiquewhite: "antiquewhite",
	Aqua: "aqua",
	Aquamarine: "aquamarine",
	Azure: "azure",
	Beige: "beige",
	Bisque: "bisque",
	Black: "black",
	Blanchedalmond: "blanchedalmond",
	Blue: "blue",
	Blueviolet: "blueviolet",
	Brown: "brown",
	Burlywood: "burlywood",
	Cadetblue: "cadetblue",
	Chartreuse: "chartreuse",
	Chocolate: "chocolate",
	Coral: "coral",
	Cornflowerblue: "cornflowerblue",
	Cornsilk: "cornsilk",
	Crimson: "crimson",
	Cyan: "cyan",
	Darkblue: "darkblue",
	Darkcyan: "darkcyan",
	Darkgoldenrod: "darkgoldenrod",
	Darkgray: "darkgray",
	Darkgreen: "darkgreen",
	Darkgrey: "darkgrey",
	Darkkhaki: "darkkhaki",
	Darkmagenta: "darkmagenta",
	Darkolivegreen: "darkolivegreen",
	Darkorange: "darkorange",
	Darkorchid: "darkorchid",
	Darkred: "darkred",
	Darksalmon: "darksalmon",
	Darkseagreen: "darkseagreen",
	Darkslateblue: "darkslateblue",
	Darkslategray: "darkslategray",
	Darkslategrey: "darkslategrey",
	Darkturquoise: "darkturquoise",
	Darkviolet: "darkviolet",
	Deeppink: "deeppink",
	Deepskyblue: "deepskyblue",
	Dimgray: "dimgray",
	Dimgrey: "dimgrey",
	Dodgerblue: "dodgerblue",
	Firebrick: "firebrick",
	Floralwhite: "floralwhite",
	Forestgreen: "forestgreen",
	Fuchsia: "fuchsia",
	Gainsboro: "gainsboro",
	Ghostwhite: "ghostwhite",
	Gold: "gold",
	Goldenrod: "goldenrod",
	Gray: "gray",
	Green: "green",
	Greenyellow: "greenyellow",
	Grey: "grey",
	Honeydew: "honeydew",
	Hotpink: "hotpink",
	Indianred: "indianred",
	Indigo: "indigo",
	Ivory: "ivory",
	Khaki: "khaki",
	Lavender: "lavender",
	Lavenderblush: "lavenderblush",
	Lawngreen: "lawngreen",
	Lemonchiffon: "lemonchiffon",
	Lightblue: "lightblue",
	Lightcoral: "lightcoral",
	Lightcyan: "lightcyan",
	Lightgoldenrodyellow: "lightgoldenrodyellow",
	Lightgray: "lightgray",
	Lightgreen: "lightgreen",
	Lightgrey: "lightgrey",
	Lightpink: "lightpink",
	Lightsalmon: "lightsalmon",
	Lightseagreen: "lightseagreen",
	Lightskyblue: "lightskyblue",
	Lightslategray: "lightslategray",
	Lightslategrey: "lightslategrey",
	Lightsteelblue: "lightsteelblue",
	Lightyellow: "lightyellow",
	Lime: "lime",
	Limegreen: "limegreen",
	Linen: "linen",
	Magenta: "magenta",
	Maroon: "maroon",
	Mediumaquamarine: "mediumaquamarine",
	Mediumblue: "mediumblue",
	Mediumorchid: "mediumorchid",
	Mediumpurple: "mediumpurple",
	Mediumseagreen: "mediumseagreen",
	Mediumslateblue: "mediumslateblue",
	Mediumspringgreen: "mediumspringgreen",
	Mediumturquoise: "mediumturquoise",
	Mediumvioletred: "mediumvioletred",
	Midnightblue: "midnightblue",
	Mintcream: "mintcream",
	Mistyrose: "mistyrose",
	Moccasin: "moccasin",
	Navajowhite: "navajowhite",
	Navy: "navy",
	Oldlace: "oldlace",
	Olive: "olive",
	Olivedrab: "olivedrab",
	Orange: "orange",
	Orangered: "orangered",
	Orchid: "orchid",
	Palegoldenrod: "palegoldenrod",
	Palegreen: "palegreen",
	Paleturquoise: "paleturquoise",
	Palevioletred: "palevioletred",
	Papayawhip: "papayawhip",
	Peachpuff: "peachpuff",
	Peru: "peru",
	Pink: "pink",
	Plum: "plum",
	Powderblue: "powderblue",
	Purple: "purple",
	Rebeccapurple: "rebeccapurple",
	Red: "red",
	Rosybrown: "rosybrown",
	Royalblue: "royalblue",
	Saddlebrown: "saddlebrown",
	Salmon: "salmon",
	Sandybrown: "sandybrown",
	Seagreen: "seagreen",
	Seashell: "seashell",
	Sienna: "sienna",
	Silver: "silver",
	Skyblue: "skyblue",
	Slateblue: "slateblue",
	Slategray: "slategray",
	Slategrey: "slategrey",
	Snow: "snow",
	Springgreen: "springgreen",
	Steelblue: "steelblue",
	Tan: "tan",
	Teal: "teal",
	Thistle: "thistle",
	Tomato: "tomato",
	Turquoise: "turquoise",
	Violet: "violet",
	Wheat: "wheat",
	White: "white",
	Whitesmoke: "whitesmoke",
	Yellow: "yellow",
	Yellowgreen: "yellowgreen",
});

#[cfg(feature = "chromashift")]
impl super::ToChromashift for NamedColor {
	fn to_chromashift(&self) -> Option<chromashift::Color> {
		use chromashift::{Color, Named};
		Some(Color::Named(match self {
			NamedColor::Aliceblue(_) => Named::Aliceblue,
			NamedColor::Antiquewhite(_) => Named::Antiquewhite,
			NamedColor::Aqua(_) => Named::Aqua,
			NamedColor::Aquamarine(_) => Named::Aquamarine,
			NamedColor::Azure(_) => Named::Azure,
			NamedColor::Beige(_) => Named::Beige,
			NamedColor::Bisque(_) => Named::Bisque,
			NamedColor::Black(_) => Named::Black,
			NamedColor::Blanchedalmond(_) => Named::Blanchedalmond,
			NamedColor::Blue(_) => Named::Blue,
			NamedColor::Blueviolet(_) => Named::Blueviolet,
			NamedColor::Brown(_) => Named::Brown,
			NamedColor::Burlywood(_) => Named::Burlywood,
			NamedColor::Cadetblue(_) => Named::Cadetblue,
			NamedColor::Chartreuse(_) => Named::Chartreuse,
			NamedColor::Chocolate(_) => Named::Chocolate,
			NamedColor::Coral(_) => Named::Coral,
			NamedColor::Cornflowerblue(_) => Named::Cornflowerblue,
			NamedColor::Cornsilk(_) => Named::Cornsilk,
			NamedColor::Crimson(_) => Named::Crimson,
			NamedColor::Cyan(_) => Named::Cyan,
			NamedColor::Darkblue(_) => Named::Darkblue,
			NamedColor::Darkcyan(_) => Named::Darkcyan,
			NamedColor::Darkgoldenrod(_) => Named::Darkgoldenrod,
			NamedColor::Darkgray(_) => Named::Darkgray,
			NamedColor::Darkgrey(_) => Named::Darkgrey,
			NamedColor::Darkgreen(_) => Named::Darkgreen,
			NamedColor::Darkkhaki(_) => Named::Darkkhaki,
			NamedColor::Darkmagenta(_) => Named::Darkmagenta,
			NamedColor::Darkolivegreen(_) => Named::Darkolivegreen,
			NamedColor::Darkorange(_) => Named::Darkorange,
			NamedColor::Darkorchid(_) => Named::Darkorchid,
			NamedColor::Darkred(_) => Named::Darkred,
			NamedColor::Darksalmon(_) => Named::Darksalmon,
			NamedColor::Darkseagreen(_) => Named::Darkseagreen,
			NamedColor::Darkslateblue(_) => Named::Darkslateblue,
			NamedColor::Darkslategray(_) => Named::Darkslategray,
			NamedColor::Darkslategrey(_) => Named::Darkslategrey,
			NamedColor::Darkturquoise(_) => Named::Darkturquoise,
			NamedColor::Darkviolet(_) => Named::Darkviolet,
			NamedColor::Deeppink(_) => Named::Deeppink,
			NamedColor::Deepskyblue(_) => Named::Deepskyblue,
			NamedColor::Dimgray(_) => Named::Dimgrey,
			NamedColor::Dimgrey(_) => Named::Dimgray,
			NamedColor::Dodgerblue(_) => Named::Dodgerblue,
			NamedColor::Firebrick(_) => Named::Firebrick,
			NamedColor::Floralwhite(_) => Named::Floralwhite,
			NamedColor::Forestgreen(_) => Named::Forestgreen,
			NamedColor::Fuchsia(_) => Named::Fuchsia,
			NamedColor::Gainsboro(_) => Named::Gainsboro,
			NamedColor::Ghostwhite(_) => Named::Ghostwhite,
			NamedColor::Gold(_) => Named::Gold,
			NamedColor::Goldenrod(_) => Named::Goldenrod,
			NamedColor::Gray(_) => Named::Gray,
			NamedColor::Grey(_) => Named::Grey,
			NamedColor::Green(_) => Named::Green,
			NamedColor::Greenyellow(_) => Named::Greenyellow,
			NamedColor::Honeydew(_) => Named::Honeydew,
			NamedColor::Hotpink(_) => Named::Hotpink,
			NamedColor::Indianred(_) => Named::Indianred,
			NamedColor::Indigo(_) => Named::Indigo,
			NamedColor::Ivory(_) => Named::Ivory,
			NamedColor::Khaki(_) => Named::Khaki,
			NamedColor::Lavender(_) => Named::Lavender,
			NamedColor::Lavenderblush(_) => Named::Lavenderblush,
			NamedColor::Lawngreen(_) => Named::Lawngreen,
			NamedColor::Lemonchiffon(_) => Named::Lemonchiffon,
			NamedColor::Lightblue(_) => Named::Lightblue,
			NamedColor::Lightcoral(_) => Named::Lightcoral,
			NamedColor::Lightcyan(_) => Named::Lightcyan,
			NamedColor::Lightgoldenrodyellow(_) => Named::Lightgoldenrodyellow,
			NamedColor::Lightgray(_) | NamedColor::Lightgrey(_) => Named::Lightgray,
			NamedColor::Lightgreen(_) => Named::Lightgreen,
			NamedColor::Lightpink(_) => Named::Lightpink,
			NamedColor::Lightsalmon(_) => Named::Lightsalmon,
			NamedColor::Lightseagreen(_) => Named::Lightseagreen,
			NamedColor::Lightskyblue(_) => Named::Lightskyblue,
			NamedColor::Lightslategray(_) => Named::Lightslategray,
			NamedColor::Lightslategrey(_) => Named::Lightslategrey,
			NamedColor::Lightsteelblue(_) => Named::Lightsteelblue,
			NamedColor::Lightyellow(_) => Named::Lightyellow,
			NamedColor::Lime(_) => Named::Lime,
			NamedColor::Limegreen(_) => Named::Limegreen,
			NamedColor::Linen(_) => Named::Linen,
			NamedColor::Magenta(_) => Named::Magenta,
			NamedColor::Maroon(_) => Named::Maroon,
			NamedColor::Mediumaquamarine(_) => Named::Mediumaquamarine,
			NamedColor::Mediumblue(_) => Named::Mediumblue,
			NamedColor::Mediumorchid(_) => Named::Mediumorchid,
			NamedColor::Mediumpurple(_) => Named::Mediumpurple,
			NamedColor::Mediumseagreen(_) => Named::Mediumseagreen,
			NamedColor::Mediumslateblue(_) => Named::Mediumslateblue,
			NamedColor::Mediumspringgreen(_) => Named::Mediumspringgreen,
			NamedColor::Mediumturquoise(_) => Named::Mediumturquoise,
			NamedColor::Mediumvioletred(_) => Named::Mediumvioletred,
			NamedColor::Midnightblue(_) => Named::Midnightblue,
			NamedColor::Mintcream(_) => Named::Mintcream,
			NamedColor::Mistyrose(_) => Named::Mistyrose,
			NamedColor::Moccasin(_) => Named::Moccasin,
			NamedColor::Navajowhite(_) => Named::Navajowhite,
			NamedColor::Navy(_) => Named::Navy,
			NamedColor::Oldlace(_) => Named::Oldlace,
			NamedColor::Olive(_) => Named::Olive,
			NamedColor::Olivedrab(_) => Named::Olivedrab,
			NamedColor::Orange(_) => Named::Orange,
			NamedColor::Orangered(_) => Named::Orangered,
			NamedColor::Orchid(_) => Named::Orchid,
			NamedColor::Palegoldenrod(_) => Named::Palegoldenrod,
			NamedColor::Palegreen(_) => Named::Palegreen,
			NamedColor::Paleturquoise(_) => Named::Paleturquoise,
			NamedColor::Palevioletred(_) => Named::Palevioletred,
			NamedColor::Papayawhip(_) => Named::Papayawhip,
			NamedColor::Peachpuff(_) => Named::Peachpuff,
			NamedColor::Peru(_) => Named::Peru,
			NamedColor::Pink(_) => Named::Pink,
			NamedColor::Plum(_) => Named::Plum,
			NamedColor::Powderblue(_) => Named::Powderblue,
			NamedColor::Purple(_) => Named::Purple,
			NamedColor::Rebeccapurple(_) => Named::Rebeccapurple,
			NamedColor::Red(_) => Named::Red,
			NamedColor::Rosybrown(_) => Named::Rosybrown,
			NamedColor::Royalblue(_) => Named::Royalblue,
			NamedColor::Saddlebrown(_) => Named::Saddlebrown,
			NamedColor::Salmon(_) => Named::Salmon,
			NamedColor::Sandybrown(_) => Named::Sandybrown,
			NamedColor::Seagreen(_) => Named::Seagreen,
			NamedColor::Seashell(_) => Named::Seashell,
			NamedColor::Sienna(_) => Named::Sienna,
			NamedColor::Silver(_) => Named::Silver,
			NamedColor::Skyblue(_) => Named::Skyblue,
			NamedColor::Slateblue(_) => Named::Slateblue,
			NamedColor::Slategray(_) => Named::Slategray,
			NamedColor::Slategrey(_) => Named::Slategrey,
			NamedColor::Snow(_) => Named::Snow,
			NamedColor::Springgreen(_) => Named::Springgreen,
			NamedColor::Steelblue(_) => Named::Steelblue,
			NamedColor::Tan(_) => Named::Tan,
			NamedColor::Teal(_) => Named::Teal,
			NamedColor::Thistle(_) => Named::Thistle,
			NamedColor::Tomato(_) => Named::Tomato,
			NamedColor::Turquoise(_) => Named::Turquoise,
			NamedColor::Violet(_) => Named::Violet,
			NamedColor::Wheat(_) => Named::Wheat,
			NamedColor::White(_) => Named::White,
			NamedColor::Whitesmoke(_) => Named::Whitesmoke,
			NamedColor::Yellow(_) => Named::Yellow,
			NamedColor::Yellowgreen(_) => Named::Yellowgreen,
		}))
	}
}

#[cfg(test)]
mod tests {
	use super::*;
	use css_parse::assert_parse;

	#[test]
	fn size_test() {
		assert_eq!(std::mem::size_of::<NamedColor>(), 16);
	}

	#[test]
	fn test_writes() {
		assert_parse!(NamedColor, "yellow");
		assert_parse!(NamedColor, "tomato");
		assert_parse!(NamedColor, "tan");
	}
}
