name: bench
on:
  pull_request:
    types: [ opened, synchronize, reopened, labeled ]
jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'bench')
    name: Benchmark on linux
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - run: rustup target add x86_64-unknown-linux-gnu
      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: release-x86_64-unknown-linux-gnu
      - id: cache-target
        name: Cache CI Benchmarks
        uses: actions/cache@v4
        with:
            key: ${{ runner.os }}-${{ github.ref }}
            path: |
                ./target/criterion
      - name: Criterion Compare PRs
        uses: boa-dev/criterion-compare-action@59f4d964c5f19d7f13d36f5c0944b18ce6652cb0
        with:
          branchName: ${{ github.base_ref }}
