name: Generate all values
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
jobs:
  build:
    name: Generate css_ast/src/values
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          submodules: 'true'
      - name: Mise
        uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac #v2.4.4
      - name: Rust cache
        uses: swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 #v2.8.0
        with:
          shared-key: global-rust-cache
      - name: Ensure cargo fmt is installed
        run: rustup component add rustfmt
      - name: Check fmt
        run: cargo fmt --check
      - name: Generate all values
        run: mise run generate-all-values
      - name: Make PR
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git update-ref -d refs/heads/generate-all-values
          git switch -c generate-all-values
          git add crates/css_ast/src/values/
          git commit --message 'Regenerate css_ast/src/values from csswg drafts' && \
          git push --force origin HEAD:refs/heads/generate-all-values && \
          gh pr create --title 'Regenerate css_ast/src/values from csswg drafts' --body "Updates to the latest specs"
          gh pr merge --auto --delete-branch --squash "$BRANCH_NAME"
          gh workflow run "test.yml" --ref "generate-all-values"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
