name: Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: ./.github/actions/rustup
        with:
          save-cache: ${{ github.ref_name == 'main' }}
          shared-key: "wasm"
      - uses: actions/setup-node@v4
        with:
          node-version: 23.x
          cache-dependency-path: ./website/package.json
          cache: "npm"
      - run: npm i --production=false
        working-directory: ./website
        env:
          NODE_ENV: production
      - run: cargo doc --all-features
      - run: mkdir -p ./website/_site/docs/internal/
      - run: cp -rf ./target/docs/* ./website/_site/doc/internal/
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "website/_site"
      - id: deployment
        uses: actions/deploy-pages@v4
