name: Pages
on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: "true"
      - name: Download benchmark history
        uses: dawidd6/action-download-artifact@8305c0f1062bb0d184d09ef4493ecb9288447732 # v20
        with:
          name: benchmark-history
          workflow: benchmark-tracking.yml
          workflow_conclusion: success
          branch: main
          search_artifacts: true
          path: website/_data
      - name: Setup
        uses: ./.github/actions/setup
        with:
          dir: ./website
      - name: Configure Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0
      - name: Add wasm target
        run: rustup target add wasm32-unknown-unknown
      - name: npm Install
        run: npm i --production=false
        working-directory: ./website
        env:
          NODE_ENV: production
      - name: Get npm cache directory
        id: npm-cache-dir
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      - name: Cache npm
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Build internal docs
        run: cargo doc --all-features --no-deps --keep-going --release
      - name: Ensure internal docs directory exists
        run: mkdir -p ./website/_site/docs/internal/
      - name: Copy internal docs to website
        run: cp -rf ./target/doc/* ./website/_site/docs/internal/
      - name: Upload website
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: "website/_site"
      - name: Deploy website
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
