# mostly copied from https://raw.githubusercontent.com/web-infra-dev/oxc/main/.github/workflows/release_cli.yml
name: test
on:
  push:
    branches: ["main"]
  pull_request:
permissions:
  contents: read
  id-token: write
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            code-target: win32-x64

          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            code-target: linux-x64

          - os: macos-latest
            target: x86_64-apple-darwin
            code-target: darwin-x64

    name: Build & Test on ${{ matrix.code-target }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - run: rustup target add ${{ matrix.target }}
      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: release-${{ matrix.target }}
      - if: matrix.os != 'windows-latest'
        run: cargo test --all-features
        env:
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc

      # Because quirks, we won't test on Windows for now. But we still should see it build
      - if: matrix.os == 'windows-latest'
        run: cargo build
