// AUTO-GENERATED from w3c/csswg-drafts
// Commit: https://github.com/w3c/csswg-drafts/commit/7292c6d8ff9e9f062af880c4a74bafa29577cd79
// Do not edit this file directly.
#![allow(warnings)]
//! https://drafts.csswg.org/css-nav-1/

mod impls;
use super::prelude::*;
use impls::*;
/// Represents the style value for `spatial-navigation-action` as defined in [css-nav-1](https://drafts.csswg.org/css-nav-1/#spatial-navigation-action).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | focus | scroll
/// ```
///
/// https://drafts.csswg.org/css-nav-1/#spatial-navigation-action
#[syntax(" auto | focus | scroll ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Unknown,
    animation_type = Discrete,
    property_group = Nav,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(feature = "css_feature_data", derive(ToCSSFeature), css_feature("css.properties.spatial-navigation-action"))]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub enum SpatialNavigationActionStyleValue {}

/// Represents the style value for `spatial-navigation-contain` as defined in [css-nav-1](https://drafts.csswg.org/css-nav-1/#spatial-navigation-contain).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// auto | contain
/// ```
///
/// https://drafts.csswg.org/css-nav-1/#spatial-navigation-contain
#[syntax(" auto | contain ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "auto",
    applies_to = Elements,
    animation_type = Discrete,
    property_group = Nav,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(
	feature = "css_feature_data",
	derive(ToCSSFeature),
	css_feature("css.properties.spatial-navigation-contain")
)]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub enum SpatialNavigationContainStyleValue {}

/// Represents the style value for `spatial-navigation-function` as defined in [css-nav-1](https://drafts.csswg.org/css-nav-1/#spatial-navigation-function).
///
/// The grammar is defined as:
///
/// ```text,ignore
/// normal | grid
/// ```
///
/// https://drafts.csswg.org/css-nav-1/#spatial-navigation-function
#[syntax(" normal | grid ")]
#[derive(
	Parse, Peek, ToSpan, ToCursors, DeclarationMetadata, SemanticEq, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
#[declaration_metadata(
    initial = "normal",
    applies_to = Unknown,
    animation_type = Discrete,
    property_group = Nav,
    computed_value_type = AsSpecified,
    canonical_order = "per grammar",
)]
#[cfg_attr(feature = "serde", derive(serde::Serialize), serde())]
#[cfg_attr(
	feature = "css_feature_data",
	derive(ToCSSFeature),
	css_feature("css.properties.spatial-navigation-function")
)]
#[cfg_attr(feature = "visitable", derive(Visitable), visit)]
pub enum SpatialNavigationFunctionStyleValue {}
